doc/man/pam_get_user.3.xml
Just a small error I came across when reading the docs.
=> Fix missing word in documentation.

modules/pam_unix/passverify.c
libxcrypt v4.3 has added the crypt_checksalt function to whether the prefix at the begining of a given hash string refers to a supported hashing method.
Future revisions of this function will add support to check whether the hashing method, the prefix refers to, was disabled or considered deprecated by the system's factory presets or system administrator.
Furthermore it will be able to detect whether the parameters, which are used by the corresponding hashing method, being encoded in the hash string are not considered to be strong enough anymore.
*modules/pam_unix/passverify.c: Add support for crypt_checksalt.
=> pam_unix: Add support for crypt_checksalt, if libcrypt supports it.

modules/pam_env/pam_env.conf
Hi,
I fixed a quick grammar error I picked up.
=> Fixed a grammer mistake

modules/pam_succeed_if/pam_succeed_if.c
Allow for conditions that just check the user field to also work for
users not known to the system. Before this caused a PAM_USER_UNKNOWN
even if no extra data for an existing user was needed. E.g.
auth sufficient pam_succeed_if.so user = NotKnownToSystem
modules/pam_succeed_if/pam_succeed_if.c (evaluate): Change the pwd
parameter to an input/output parameter. Lazily request pwd with
pam_modutil_getpwnam() if needed and return PAM_USER_UNKNOWN on failure.
modules/pam_succeed_if/pam_succeed_if.c (pam_sm_authenticate): Don't
request the pwd if !use_uid anymore and shift the output from audit to
after the evaluate() call. Also make sure not to give the normal failure
message if the lazy pwd loading failed.
=> pam_succeed_if: Request user data only when needed

NEWS, configure.ac
The latest release was made almost 5 months ago, let's prepare for the next one.
=> Prepare for the next release

modules/pam_umask/pam_umask.c
Potential failures of strdup(3) were ignored, fix this by not using
strdup(3) at all.
* modules/pam_umask/pam_umask.c (struct options_t): Add const to umask
field, add login_umask field.
(parse_option): Do not use strdup.
(get_options): Assign pam_modutil_search_key return values
to options->login_umask.
(pam_sm_open_session): Free options.login_umask instead of
options.umask.
=> pam_umask: fix handling of umask parameter

modules/pam_access/pam_access.c
* modules/pam_access/pam_access.c (from_match): Split out remote_match()
function and avoid calling it when matching against LOCAL keyword.
=> pam_access: clean up the remote host matching code

doc/man/pam_end.3.xml
=> man: fix spelling bug in pam_end.3.xml

examples/xsh.c
=> fix: typing error

modules/pam_nologin/pam_nologin.c
Conversation functions most of the time add an extra "\n" to messages from PAM modules. This leads to disturbing line breaks and empty lines in the output.
Better to do not print an empty message at all.
=> pam_nologin: don't print empty message

modules/pam_access/pam_access.c
According to the manual page, the following entry is valid but does not work:
-:root:ALL EXCEPT localhost
See https://bugzilla.suse.com/show_bug.cgi?id=1019866
Patched is based on PR#226 from Josef Moellers
=> pam_access: handle hostnames in access.conf

modules/pam_issue/pam_issue.c
Move definitions of static functions before their first use
to avoid forward declarations cluttering the code.
=> pam_issue: reorder definitions of static functions to avoid forward declarations

doc/sag/Linux-PAM_SAG.xml
=> doc: add pam_faillock module to SAG

modules/pam_lastlog/pam_lastlog.c
Fixed 2 instances where file locks were not being enforced.
=> pam_lastlog: fix file locking

doc/Makefile.am
doc/Makefile.am: Replace custom-html.xsl and custom-man.xsl with
custom-html.xsl.in and custom-man.xsl.in EXTRA_DIST
=> doc: Include custom-html.xsl.in and custom-man.xsl.in

modules/pam_limits/pam_limits.c
Even if this module is supported officially on Linux, make sure it can still build fine on non-Linux OSes, to ease its testing/fixing a bit:
- build `parse_kernel_limits()` and stuff needed for it only on Linux, as it is called already only on Linux
- limit the code needed to apply the 'nonewprivs' options to Linux only, as it uses a Linux-specific way to set it; add a syslog message for other OSes
=> pam_limits: build again on non-Linux OSes

modules/pam_mkhomedir/mkhomedir_helper.c
To support OSes without PATH_MAX (which is optional in POSIX), there are two code paths for the `newsource` and `newdest` variables: one using a PATH_MAX-sized stack buffer, and one using heap allocation. The second is even more complicated than needed, doing manual calculations and allocations.
To simplify the code a bit more, easing its maintenance, unify the two using `asprintf()` to allocate `newsource` and `newdest`: the extra allocation needed should not be an issue, since this code runs in a separate helper executable.
As additional change for this simplification, remove the reset to the two variables to NULL right after their `free()`, which is not needed since their scopes end.
=> pam_mkhomedir: simplify handling of newsource/newdest

modules/pam_xauth/pam_xauth.c
Allocate the path buffer in `check_acl()` dynamically using `asprintf()`, so there is no need to use a PATH_MAX-fixed size buffer. The fallback PATH_MAX definition is no more needed, thus is dropped.
Make sure that paths too long still result in `PAM_SESSION_ERR`.
=> pam_xauth: switch away from PATH_MAX

configure.ac, modules/pam_userdb/pam_userdb.c
* configure.ac: add `gdbm` option to `enable-db`
* modules/pam_userdb/pam_userdb.c: conditionally provide database access depending on the database technology
=> pam_userdb: enable GDBM support

modules/pam_xauth/pam_xauth.c
Passing an indeterminate number of arguments via varargs to a function is dependent on the compiler implementation. Instead, as we are handing off the argv to execv directly anyway without further processing we can build this array inline at the call site instead.
Doing so actually also avoids a previous limitation of the old implementation where long argument lists could have been truncated silently to their first nine arguments. The new implementation does not impose such a limit on the caller.
=> pam_xauth: avoid building argv inside run_coprocess

libpam/pam_handlers.c
This is much easier to read, does the same and is less prone to getting `memcpy` and `strcpy` wrong.
=> libpam: Simplify mod_path string building logic

modules/pam_faildelay/pam_faildelay.c
The function sscanf does not verify that a value parsed with %ld is actually within the valid range of a long, allowing silent truncation.
When parsing FAIL_DELAY from login.defs, a mask of 0777 is applied before performing range checks for strtol return value. Since this mask does not make sense here, it is removed.
With these changes, values smaller than 0 or larger than UINT_MAX, which is the actual limit for pam_fail_delay, are discarded and logged.
1. Use `FAIL_DELAY=512` in /etc/login.defs
2. Use `auth      optional    pam_faildelay.so` in e.g. /etc/pam.d/su
3. Perform an invalid login with su
4. The timeout is merely a second, not 512 seconds
=> pam_faildelay: validate parameter ranges

modules/pam_unix/support.c
It is possible to have a mismatch between ENCRYPT_METHOD in login.defs and an argument given specifically to pam_unix.so.
If pam_unix.so receives the argument "yescrypt" but ENCRYPT_METHOD is set to SHA512, then SHA_CRYPT_MAX_ROUNDS is parsed from login.defs and used as rounds for yescrypt -- except if rounds are specificially given as an argument to pam_unix.so as well.
Read the correct rounds from login.defs after all arguments are parsed and no rounds were specified to figure out which one will eventually be used.
1. Use the following lines in /etc/login.defs
```
ENCRYPT_METHOD SHA512
SHA_CRYPT_MAX_ROUNDS 9
YESCRYPT_COST_FACTOR 5
```
2. Configure pam_unix.so for passwd in e.g. /etc/pam.d/system-password
```
password  required    pam_unix.so       yescrypt shadow …
```
=> pam_unix: use correct number of rounds

modules/pam_unix/passverify.c, modules/pam_unix/support.c
Print an error in syslog if an integer could not be converted.
This prevents working with incorrectly parsed values from e.g. /etc/login.defs.
1. Use following pam_unix.so configuration for passwd in e.g. /etc/pamd./system-password
```
password  required    pam_unix.so       yescrypt shadow try_first_pass minlen=4294967296
```
2. Try to change password with passwd
```
$ passwd
```
3. Notice that you can use any length of password and no error in syslog
With this patch, syslog will contain `pam_unix(passwd:chauthtok): option minlen invalid [4294967296]`.
=> pam_unix: check str to integer conversions

modules/pam_unix/passverify.c
It is possible to trigger signed integer overflows in check_shadow_expiry if /etc/shadow contains very large values.
Since these values have to be set by a system administrator, it would already count as a configuration error.
Yet, avoid overflows which would consider accounts which are supposed to be valid for a veeery long time as already invalid. Also, it would be undefined behavior for almost all C standards.
Also consider every negative value as invalid, not just -1. The shadow project has different ways of handling these values, but this approach is in sync with its lib/isexpired.c implementation.
A proof of concept is quite difficult. On 64 bit systems, it takes a getspent implementation which actually supports long (glibc caps at INT_MAX, shadow's getspent would work). The easiest …
=> pam_unix: fix possible shadow signed overflows

modules/pam_limits/pam_limits.c
Even though sscanf is easy to use for scanning strings, it has the drawback that the required memory has to be allocated beforehand.
Since variable "line" is not accessed anymore after sscanf, it is easier to point into the memory assigned to "line". The function strtok_r can be used as a replacement for sscanf.
=> pam_limits: avoid sscanf in parse_config_file

libpam/pam_misc.c
The input string "s" is duplicated into "sbuf" and tokens copied from there into target memory "our_argv".
Since "our_argv" is allocated to be always large enough to keep the whole string "s" (plus pointers) in it, we can skip "sbuf" entirely.
=> libpam: reduce memory usage of _pam_mkargv

modules/pam_listfile/Makefile.am, modules/pam_listfile/tst-pam_listfile-retval.c
* modules/pam_listfile/tst-pam_listfile-retval.c: New file.
* modules/pam_listfile/Makefile.am (TESTS): Add $(check_PROGRAMS).
(check_PROGRAMS, tst_pam_listfile_retval_LDADD): New variables.
=> pam_listfile: add a test for return values

modules/pam_namespace/namespace.conf.5.xml, modules/pam_namespace/pam_namespace.8.xml, modules/pam_namespace/pam_namespace.c
I recently performed a security code audit of `pam_namespace` and noticed a couple of things that I want to address with this PR#.
=> pam_namespace: bugfixes, security improvements, documentation improvements

modules/pam_unix/pam_unix_passwd.c
The function `_unix_comesfromsource` calls `_unix_getpwnam` internally. When changing the authentication token, it is first called to read local passwd file and optionally contacting NIS. If an entry is found, `_unix_getpwnam` is called, this time definitely reading passwd file and contacting NIS (if support exists) and parsing the entry.
This is meant to check if the entry is not just available but also valid.
Since the return value of `_unix_getpwnam` is not checked and the supplied pointer is only set in case of success, the check for a NULl pointer afterwards can lead to undefined behavior.
It is easier to call `_unix_getpwnam` directly, check its return value and then check if the entry could be parsed. This in turn reduces the amount of /etc/passwd accesses (and fixes a theoretical …
=> pam_unix: avoid reading uninitialized variable

libpam/pam_delay.c
If a delay close to UINT_MAX has been set, then the delay computation might overflow the value due to added randomness.
Systems where linux-pam is in use should generally have a 32 bit unsigned int and a 64 bit unsigned long long, and a time_t of either 64 bit or 32 bit. Under these assumptions, using the result for delay is safe because of the division before assigning it to tv_sec (time_t).
Thought about using uint64_t type here but as long as "unsigned int" is part of the API instead of uint32_t, no proper guarantees could be made anyway.
Unfortunately we have to supply an unsigned int if a PAM_FAIL_DELAY function has been set. In such a case, supply a UINT_MAX if delay is larger than that. It's the best we can do without breaking the API.
1. Compile Linux-PAM with …
=> libpam: handle long delays properly

modules/pam_limits/pam_limits.c
The strcpy is not safe anymore because input lines can be very long. Use strdup instead. If allocation fails, treat the error exactly like a memory allocation issue in pam_modutil functions.
Fixes issue which was introduced in 13dc0a7754d7978c6fc69ca2e0021e9193a8b0aa.
No release affected.
=> pam_limits: prevent overflow with very long line

modules/pam_debug/pam_debug.c, modules/pam_exec/pam_exec.c, modules/pam_pwhistory/opasswd.c, modules/pam_securetty/pam_securetty.c
Simplify code where easily possible.
=> treewide: simplify code

modules/pam_unix/Makefile.am, modules/pam_unix/audit.c, modules/pam_unix/audit.h, modules/pam_unix/bigcrypt.c, modules/pam_unix/lckpwdf.-c, modules/pam_unix/md5_crypt.c, modules/pam_unix/pam_unix_passwd.c, modules/pam_unix/pam_unix_sess.c, modules/pam_unix/passverify.c, modules/pam_unix/passverify.h, modules/pam_unix/support.c, modules/pam_unix/support.h, modules/pam_unix/unix_chkpwd.c, modules/pam_unix/unix_update.c
See single commit descriptions for more information.
=> pam_unix updates

modules/pam_unix/support.c, modules/pam_xauth/pam_xauth.c
=> Misc string issues

modules/pam_limits/pam_limits.c
pl->conf_file points to filename_list[i]
filename_list and its contents were freed but we still attempt to use it in log.
=> pam_limits: fix use-after-free of pl->conf_file

modules/pam_issue/pam_issue.c
systemd added new types of classes (e.g. manager*). So we cannot use the count of all sessions anymore, but have to check which class this is.
This is backward compatible, systemd v209 or newer is required.
=> pam_issue: only count class user
