modules/pam_cracklib/pam_cracklib.c
I'm Saul, a researcher at Teesside University, UK. We use `pam_cracklib` in our teaching and found what seems to be a bug when the `maxclassrepeat` option is set to `1`. Myself, along with researchers from the university's [Software Reliability Lab](https://github.com/sr-lab) discovered the following:
If `maxclassrepeat` is set to a number greater than `1` it behaves as expected. For instance setting it to `3` would cause the following password to be flagged as 'too simple':
```
myfavouritesong
```
Due to it containing more than 3 lowercase letters in a row. This is consistent with the documentation.
However, setting `maxclassrepeat` to `1` would result in the example above being allowed. This is due to a check done in `pam_cracklib.c` [line …
=> Make maxclassrepeat=1 behavior consistent with docs

modules/pam_unix/pam_unix_auth.c
Check the return value of malloc and if it failed print debug info, send
a syslog message and return an error code.
Signed-off-by: Peter Urbanec <git.user@urbanec.net>
=> pam_unix: Check return value of malloc used for setcred data

modules/pam_motd/pam_motd.8.xml, modules/pam_motd/pam_motd.c
Add a new feature to pam_motd to allow packages to install their own
message files in a "motd.d" directory, to be displayed after the primary
motd.
Add an option motd_d= to specify the location of this directory.
Modify the defaults, in the case where no options are given, to display
both /etc/motd and /etc/motd.d.
Fixes #47
* modules/pam_motd/pam_motd.c: add support for motd.d
* modules/pam_motd/pam_motd.8.xml: update the manpage
=> pam_motd: add support for a motd.d directory

modules/pam_unix/passverify.c
Bcrypt hashes used the "$2a$" prefix since 1997.
However, in 2011 an implementation bug was discovered in bcrypt affecting the handling of characters in passphrases with the 8th bit set.
Besides fixing the bug, OpenBSD 5.5 introduced the "$2b$" prefix for a behavior that exactly matches crypt_blowfish's "$2y$", and the crypt_blowfish implementation supports it as well since v1.1.
That said new computed bcrypt hashes should use the "$2b$" prefix.
* modules/pam_unix/passverify.c: Use bcrypt b-variant.
=> pam_unix: Use bcrypt b-variant for computing new hashes.

modules/pam_motd/pam_motd.8.xml, modules/pam_motd/pam_motd.c, xtests/.gitignore, xtests/Makefile.am, xtests/tst-pam_motd.c, xtests/tst-pam_motd.sh, xtests/tst-pam_motd1.pamd, xtests/tst-pam_motd1.sh, xtests/tst-pam_motd2.pamd, xtests/tst-pam_motd2.sh, xtests/tst-pam_motd3.pamd, xtests/tst-pam_motd3.sh
This adds to `pam_motd.c` functions to parse a string of colon-separated directories as arguments for `motd` and `motd_dir`, and check for overriding filenames before displaying the motds. This also displays the motds in lexicographic order of the filenames, after merging the files contained in each directory.
Tests are added to verify the previous single-directory functionality works, as well as with multiple directories, and with symlinks.
If this is suitable to have in PAM, I will also update the documentation in this PR.
Appreciate your review and feedback!
Closes #68
=> pam_motd: Add support for specifying multiple motd directories

modules/pam_motd/pam_motd.c, xtests/Makefile.am, xtests/tst-pam_motd.sh, xtests/tst-pam_motd4.pamd, xtests/tst-pam_motd4.sh
This fixes a regression introduced by #69, where motd_path was set
to NULL and passed into strdup() if the motd_dir argument was
not specified in the configuration file. This caused a segmentation
fault.
* modules/pam_motd/pam_motd.c: fix checks for NULL in arguments
* xtests/Makefile.am: add test scripts and config file
* xtests/tst-pam_motd.sh: add running tst-pam_motd4.sh
* xtests/tst-pam_motd4.pamd: create
* xtests/tst-pam_motd4.sh: create
=> pam_motd: Fix segmentation fault when no motd_dir specified

modules/pam_unix/pam_unix_passwd.c, modules/pam_unix/passverify.c, modules/pam_unix/support.c
* modules/pam_unix/passverify.c: Prefer gensalt with auto entropy.
* modules/pam_unix/support.c: Use sane rounds for gensalt auto entropy.
=> pam_unix: Prefer a gensalt function, that supports auto entropy.

modules/pam_unix/pam_unix.8.xml, modules/pam_unix/pam_unix_acct.c, modules/pam_unix/pam_unix_auth.c, modules/pam_unix/pam_unix_passwd.c, modules/pam_unix/pam_unix_sess.c, modules/pam_unix/passverify.c, modules/pam_unix/passverify.h, modules/pam_unix/support.c, modules/pam_unix/support.h
libxcrypt (v4.2 and later) has added support for the yescrypt hashing method; gost-yescrypt has been added in v4.3.
* modules/pam_unix/passverify.c: Add support for (gost-)yescrypt.
* modules/pam_unix/support.c: Set sane rounds for (gost-)yescrypt.
* modules/pam_unix/support.h: Add support for (gost-)yescrypt.
***
Needs #73 to be merged as prerequisite.
=> pam_unix: Add support for (gost-)yescrypt hashing methods.

modules/pam_unix/pam_unix.8.xml, modules/pam_unix/passverify.c, modules/pam_unix/support.h
libxcrypt since v4.4.0 supports a default method for its gensalt function on most system configurations.  As the default method is to be considered the strongest available hash method, it should be preferred over all other hash methods supported by pam.
* modules/pam_unix/pam_unix.8.xml: Documentation for crypt_default.
* modules/pam_unix/passverify.c: Add crypt_default method.
* modules/pam_unix/support.h: Likewise.
***
@t8m  After this one, I'll open a PR for the no-MD5-fallback patch.
=> pam_unix: Add crypt_default method, if supported.

configure.ac, modules/Makefile.am, modules/pam_exec/pam_exec.c, modules/pam_rhosts/pam_rhosts.c
These are a few patches that are kept in OpenWrt in order to fix compilation with musl. These should be the non-OpenWrt specific ones.
=> Fix build on OpenWrt

modules/pam_lastlog/pam_lastlog.c
pam_lastlog module will not log info about failed login if the module
was configured with the "silent" option, or the session was opened with
PAM_SILENT flag.
Example use case enabled by this change:
sudo --non-interactive program
If this command is run by another program expecting specific output from
the command run by sudo, the unexpected info about failed logins will
break this program.
* modules/pam_lastlog/pam_lastlog.c: Respect silent option.
(last_login_failed): Skip info if LASTLOG_QUITE bit is set.
=> pam_lastlog: Respect silent option

modules/pam_lastlog/pam_lastlog.8.xml
The silent option explicitly silents only the last login message and not
bad logins. Add a note to the manual to make this clear.
* modules/pam_lastlog/pam_lastlog.8.xml: Clearify "silent showfailed"
=> pam_lastlog: Improve silent option documentation

doc/man/pam_conv.3.xml
Hi, just a simple typo fix (with a preposition changed too).
=> Fix a typo in the documentation

modules/pam_wheel/pam_wheel.8.xml
By default, pam_wheel checks for applicant membership in the wheel group
for *all* access requests, regardless of whether the target user is root
or non-root. Only if root_only is provided does it limit the membership
check to cases when the target user is root. Update the documentation to
reflect this.
=> Fix documentation for pam_wheel

modules/pam_tally2/pam_tally2.c
pam_tally2 does fsync() after writing to a tally file.
This causes hard drive cache flushes on every failed SSH login on many
(if not most) filesystems.
And an internet-exposed machine can have a lot of these failed logins.
This operation however doesn't seem to be necessary - the pam_tally2
module does not do any operation which would need explicit post-crash
ordering, it just does simple file reads and writes.
And doing a fsync() after them doesn't close any race if the system happens
to crash between a write being posted and its fsync() completion.
Let's remove this operation to get rid of all these extra cache flushes.
=> pam_tally2: Remove unnecessary fsync()

configure.ac, libpam/pam_modutil_sanitize.c
Using an arbitrary MAX_FD_NO (set to 65535 or 2000000) isn't optimal. This minor patch tries to close only open descriptors beyond STDERR_FILENO thanks to /proc/self/fd. If /proc isn't mounted, fallback to the previous behavior.
=> libpam/pam_modutil_sanitize.c: optimize the way to close fds

modules/pam_pwhistory/opasswd.c
The glibc implementation of getline/getdelim does not guarantee a NUL
terminator in lineptr if getline returns failure (-1).  This occurs when
the opasswd file exists but is empty.  Since strdup is called
immediately afterwards, this causes strdup to read uninitialized memory
and possibly buffer overrun / crash.
This also fixes a memory leak which always occurs when reading the last
line of the opasswd file.  Since the strdup is called before checking
the return code from getline, getdelim, or fgets+strlen, it will
duplicate and never free either:
- The last successfully read line (for getline or getdelim)
- Uninitialized data (if the file is empty)
- A 0 byte string (for fgets+strlen)
Fix by always checking the return code of getline, getdelim, or
fgets+strlen before calling strdup.
=> pwhistory: fix read of uninitialized data and memory leak when modifying opasswd

Make.xml.rules, configure.ac, doc/Makefile.am, doc/custom-html.xsl, doc/custom-man.xsl, doc/man/Makefile.am, doc/man/pam.8.xml, libpam/Makefile.am, libpam/pam_handlers.c, libpam/pam_modutil_searchkey.c, libpam/pam_private.h, modules/pam_securetty/Makefile.am, modules/pam_securetty/pam_securetty.8.xml, modules/pam_securetty/pam_securetty.c
With this, it is possible for Linux distributors to store their
supplied default configuration files somewhere below /usr, while
/etc only contains the changes made by the user. The new option
--enable-vendordir defines where Linux-PAM should additional look
for pam.d/*, login.defs and securetty if this files are not in /etc.
libeconf is a key/value configuration file reading library, which
handles the split of configuration files in different locations
and merges them transparently for the application.
=> Add support for a vendor directory and libeconf

configure.ac
If a compiler definition contains the spaces (e.g. CC="ccache gcc"), configure script produces a message:
./configure: line 13713: test: too many arguments
./configure: line 13740: test: too many arguments
=> Fixed missing quotes in configure script

modules/pam_nologin/pam_nologin.8.xml, modules/pam_rootok/pam_rootok.8.xml
Fixed the provided module type in pam_nologin and pam_rootok (acct -> account).
=> doc: fix module type written in MODULE TYPES PROVIDED

doc/man/pam_start.3.xml
=> Fix a typo in pam_start(3) man page

modules/pam_umask/pam_umask.c, modules/pam_unix/pam_unix_auth.c, modules/pam_unix/pam_unix_passwd.c
This is more in conformance with how other message priorities are chosen.
=> Lower "bad username" log priority

modules/pam_keyinit/pam_keyinit.8.xml, modules/pam_keyinit/pam_keyinit.c
Adds an auth module to pam_keyinit, whose implementation of
pam_sm_setcred
is identical to the implementation of pam_sm_open_session.
It is useful with PAM applications, which call pam_setcred,
before calling pam_open_session. It closes #149.
=> Adds an auth module to pam_keyinit

modules/pam_motd/pam_motd.8.xml, modules/pam_motd/pam_motd.c
This is a useful indication for update-motd profile.d snippet which can
also try to show MOTD when it is not already shown.
The use-case for that is showing MOTD in shells in containers without
PAM being involved.
=> pam_motd: Export MOTD_SHOWN=pam after showing MOTD

modules/pam_motd/pam_motd.8.xml, modules/pam_motd/pam_motd.c
Follow-up for c81280b16e1831ab0bdd0383486c7e2d1eaf1b5e.
=> Keep returning only PAM_IGNORE from pam_motd

modules/pam_access/pam_access.c
IPv6 address prefix sizes larger than 128 (i.e. not larger or equal to) should
be discarded. Additionally, for IPv4 addresses, the largest valid prefix size
should be 32.
This fixes #161
=> Fix (IPv6) address prefix size matching

configure.ac, modules/pam_umask/pam_umask.8.xml, modules/pam_umask/pam_umask.c
This change adds a configure option to set the default value of the
usergroups option (of the pam_umask module) at build-time.
Distributions usually makes the decision if usergroups should be used or
not. This allows them to control the built-in default value, without
having to ship the value in a config file (cluttering up the view
of actually relevant user/system configuration overrides).
=> pam_umask: build-time usergroups option default

doc/man/misc_conv.3.xml, doc/man/pam_get_item.3.xml, doc/man/pam_prompt.3.xml, doc/man/pam_putenv.3.xml, doc/man/pam_set_item.3.xml, modules/pam_cracklib/pam_cracklib.8.xml, modules/pam_env/pam_env.8.xml, modules/pam_env/pam_env.conf, modules/pam_exec/pam_exec.8.xml, modules/pam_filter/pam_filter.c, modules/pam_lastlog/pam_lastlog.8.xml, modules/pam_namespace/pam_namespace.c, modules/pam_timestamp/pam_timestamp_check.8.xml
A collection of spelling and grammar fixes identified by Debian's static analysis tools and Debian's users.
=> Debian spellcheck

modules/pam_rootok/pam_rootok.c
According to the man pages, "Each invocation of va_start() must be matched by a corresponding invocation of va_end() in the same function."
=> Add missing va_end() call

modules/pam_unix/passverify.c
helper_verify_password's variable salt is not just the salt but the whole hash. Renamed for clarity and conformity with the rest of the code.
=> Changed variable salt to hash

modules/pam_unix/pam_unix.8.xml, modules/pam_unix/passverify.c
If the call to the crypt(3) function failed for some reason during hashing a new login passphrase, the wrapper function for computing a hash with the md5crypt method was called internally by the pam_unix module in previous versions of linux-pam.
With CVE-2012-3287 in mind, the md5crypt method is not considered to be a safe nor recommended hashing method for a new login passphrase since at least 2012.  Thus pam_unix should error out in case of a failure in crypt(3) instead of silently computing a hashed passphrase using a potentially unsafe method.
* modules/pam_unix/pam_unix.8.xml: Update documentation.
* modules/pam_unix/passverify.c (create_password_hash): Return NULL
on error instead of silently invoke crypt_md5_wrapper().
***
As this is a long standing downstream patch from Fedora / …
=> pam_unix: Return NULL instead of calling crypt_md5_wrapper().

configure.ac, modules/Makefile.am, modules/pam_usertype/Makefile.am, modules/pam_usertype/README.xml, modules/pam_usertype/pam_usertype.8.xml, modules/pam_usertype/pam_usertype.c, modules/pam_usertype/tst-pam_usertype
This module will check if the user account type is system or regular based
on its uid. To evaluate the condition it will use 0-99 reserved range
together with `SYS_UID_MIN` and `SYS_UID_MAX` values from `/etc/login.defs`.
If these values are not set, it uses configure-time defaults
`--with-sys-uid-min` and `--with-uid-min` (according to `login.defs` man page
`SYS_UID_MAX` defaults to `UID_MIN - 1`.
This information can be used to skip specific module in pam stack
based on the account type. `pam_succeed_if uid < 1000` is used at the moment
however it does not reflect changes to `login.defs`.
=> pam_usertype: new module to tell if uid is in login.defs ranges

modules/pam_tally/pam_tally.8.xml, modules/pam_tally2/pam_tally2.8.xml
Update man page to indicate silent hides account lock notices.
Closes #160.
=> Updating man pages to indicate account leakage without silent

modules/pam_issue/pam_issue.c, modules/pam_loginuid/pam_loginuid.c, modules/pam_selinux/pam_selinux.c, modules/pam_sepermit/pam_sepermit.c, modules/pam_shells/pam_shells.c, modules/pam_tally2/pam_tally2.c, modules/pam_unix/pam_unix_passwd.c, modules/pam_xauth/pam_xauth.c
There are some source code including the same header file redundantly.
We remove these redundant header file inclusion.
=> Remove redundant header file inclusion

modules/pam_succeed_if/pam_succeed_if.8.xml, modules/pam_succeed_if/pam_succeed_if.c
There is no way to check if user is a member of any group from the list like with an attribute from passwd struct for example.
Examples:
account    requisite    pam_succeed_if.so user ingroup group1:group2
OR
account    requisite    pam_succeed_if.so user notingroup group1:group2
Can be very convenient to grant access based on complex group memberships(LDAP, etc)
=> Adding check if user is member of any group from the list.(pam_succeed_if.c)

modules/pam_unix/pam_unix.8.xml, modules/pam_unix/pam_unix_acct.c, modules/pam_unix/support.c, modules/pam_unix/support.h
Adding nullresetok to auth phase of pam_unix module will allow users
with blank password to authenticate in order to immediatelly change
their password even if nullok is not set.
This allows to have blank password authentication disabled but still
allows administrator to create new user accounts with expired blank
password that must be changed on the first login which is common
approach with many desktop environments.
=> pam_unix: add nullresetok option to allow reset blank passwords

configure.ac, modules/pam_namespace/Makefile.am, modules/pam_namespace/namespace.conf, modules/pam_namespace/pam_namespace.service.in, modules/pam_namespace/pam_namespace_helper.8.xml, modules/pam_namespace/pam_namespace_helper.in
When using polyinstantiation for /tmp and/or /var/tmp, pam_namespace
creates subdirectories with fixed name tmp-inst. These paths should be
secured as early as possible to avoid that somehow these directories
could created and controlled by for example a malicious user or
service.
Ship a tmpfiles.d drop-in file, which creates the directories early in
boot sequence with correct permissions and ownership.
Closes #111.
Signed-off-by: Topi Miettinen <toiwoton@gmail.com>
=> pam_namespace: secure tmp-inst directories

libpamc/include/security/pam_client.h, libpamc/libpamc.h, libpamc/pamc_converse.c, libpamc/test/regress/test.libpamc.c, modules/pam_timestamp/sha1.c, modules/pam_timestamp/sha1.h
Fixes issue of compiling against musl libc.
=> libpamc: Use ISO C99 uintX_t types instead of u_intX_t

modules/pam_tty_audit/pam_tty_audit.c
if kernel audit is disabled and pam audit is enabled don't fail when user tries to log in, instead syslog a warning and succeed
=> pam_tty_audit: if kernel audit is disabled don't fail when user tries to log in

configure.ac
Configure script incorrectly used a non-cached variable (ac_lib) in the
cached code path. This results in no -lcrypt being defined resulting in
link errors on a re-build.
Update configure.ac to use ac_cv_search_crypt (via ac_res) to setup the
correct library arguments.
Signed-off-by: Mark Wutzke <mark.wutzke@alliedtelesis.co.nz>
Signed-off-by: Chris Packham <chris.packham@alliedtelesis.co.nz>
=> Use cached 'crypt' library result correctly

README
Add small note to the README to point people to the CI scripts for dependency issues.
Closes #174
=> Adding package dependency hints to README

modules/pam_selinux/pam_selinux.c
Explanation: check whether unknown object classes or permissions are allowed or denied in the current policy
Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=1680961
=> pam_selinux: check unknown object classes or permissions in current policy

modules/pam_timestamp/pam_timestamp.c
_PATH_VARRUN already provides trailing slash for building paths
Fixes:
$ strings /usr/lib64/security/pam_timestamp.so | grep /run/
/var/run//pam_timestamp
/var/run//pam_timestamp/_pam_timestamp_key
=> pam_timestamp: Fix // in TIMESTAMPDIR

modules/pam_unix/pam_unix.8.xml
According to crypt(5), md5 should not be used for new hashes. Let's
give a more modern example with sha512 and 500000 rounds (default 5000
is too weak).
Signed-off-by: Topi Miettinen <toiwoton@gmail.com>
=> pam_unix: modernize example in manual page

configure.ac, doc/sag/pam_setquota.xml, modules/Makefile.am, modules/pam_setquota/Makefile.am, modules/pam_setquota/README.xml, modules/pam_setquota/pam_setquota.8.xml, modules/pam_setquota/pam_setquota.c, modules/pam_setquota/tst-pam_setquota
This module makes disk quotas usable with central user databases, such as MySQL or
LDAP.
Resolves: #92
=> pam_setquota: new module to set or modify disk quotas on session start

modules/pam_namespace/Makefile.am
Currently pam_namespace.service is installed into /usr/lib/systemd, not /usr/lib/systemd/system where it belongs.
=> Use correct path for pam_namespace.service file

modules/pam_faillock/faillock.c
Nowadays, /run/faillock/$USER files have user:root ownership and 0600 permissions. This forces the process that writes to these files to have CAP_DAC_OVERRIDE capabilites. Just by changing the permissions to 0660 the capability can be removed, which leads to a more secure system.
Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=1661822
=> pam_faillock: change /run/faillock/$USER permissions to 0660

modules/pam_unix/passverify.c, modules/pam_unix/support.c, modules/pam_usertype/pam_usertype.c
Taking a look at the time for the password prompt to appear it was possible to determine if a user existed in a system. Solved it by matching the runtime until the password prompt was shown by always checking the password hash for an existing and a non-existing user.
Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=1629598
=> match the runtime until password prompt of existing and non-existing users

configure.ac
Or change documentation to `--with-kerneloverflowuid`.
=> Fix typo on --with-kernel-overflow-uid

modules/pam_wheel/pam_wheel.8.xml, modules/pam_wheel/pam_wheel.c
modules/pam_wheel/pam_wheel.c: if getlogin fails to obtain the real user
ID, then try with PAM_RUSER. Besides, improve indentation.
modules/pam_wheel/pam_wheel.8.xml: indicate that use_uid option uses the
real uid of the calling process.
Resolves:
https://bugzilla.redhat.com/show_bug.cgi?id=1866866
=> pam_wheel: if getlogin fails fallback to PAM_RUSER

modules/pam_unix/unix_chkpwd.c
When running systemd service with DynamicUser being set, the dynamic UID
might be not mapped to user name (/etc/nsswitch.conf is not configured
with systemd nss module).
The getuidname() routine might return NULL and this is not checked by callee.
Signed-off-by: Anton D. Kachalov <rnouse@google.com>
=> Prevent SEGFAULT for unknown UID

modules/pam_namespace/pam_namespace.8.xml
modules/pam_namespace/pam_namespace.8.xml: delete obsolete information
about polyinstantiation and refer to gdm's documentation.
Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=1861841
=> pam_namespace: polyinstantiation refer to gdm doc

modules/pam_faillock/pam_faillock.c
args_parse function pass "conf=" argument to set_conf_opt() after handling by self.
set_conf_opt is not able to handle "conf" argument and write error:
sddm-helper[415]: pam_faillock(sddm:auth): Unknown option: conf
=> pam_faillock: fix invalid error message

NEWS, modules/pam_motd/pam_motd.8.xml, modules/pam_motd/pam_motd.c
modules/pam_motd/pam_motd.c: filter motd by user and group owning the
proper files. This is achieved by changing the ids of the process
reading the files from root to the target user.
Resolves:
https://bugzilla.redhat.com/show_bug.cgi?id=1861640
=> pam_motd: filter motd by user and group

configure.ac, libpam/pam_modutil_sanitize.c
This reverts commit 1b087edc7f05237bf5eccc405704cd82b848e761.
Fixes #266
=> Revert "libpam/pam_modutil_sanitize.c: optimize the way to close fds"

modules/pam_motd/pam_motd.c
modules/pam_motd/pam_motd.c: set NULL value instead of "key user" for the
prompt when dropping privileges.
=> pam_motd: unset prompt value to drop privileges

libpam/pam_dispatch.c, modules/pam_faillock/main.c, modules/pam_ftp/pam_ftp.c
libpam/pam_dispatch: remove store statement since the value is never
read.
modules/pam_faillock/main.c: remove store statement since the value is
only read in the enclosing expression.
modules/pam_ftp/pam_ftp.c: free anon_user before returning as it may be
still in use.
=> 3 covscan issues

modules/pam_env/pam_env.c
Fixes #263
* modules/pam_env/pam_env.c (_assemble_line): Do not error out if at feof()
=> pam_env: allow environment files without EOL at EOF

libpam/pam_end.c, libpam/pam_start.c
Found with AddressSanitzer in pam_wrapper tests.
==985738== 44 bytes in 4 blocks are definitely lost in loss record 18 of 18
==985738==    at 0x4839809: malloc (vg_replace_malloc.c:307)
==985738==    by 0x48957E1: _pam_strdup (pam_misc.c:129)
==985738==    by 0x489851B: _pam_start_internal (pam_start.c:85)
==985738==    by 0x4849C8C: libpam_pam_start_confdir (pam_wrapper.c:418)
==985738==    by 0x484AF94: pwrap_pam_start (pam_wrapper.c:1461)
==985738==    by 0x484AFEE: pam_start (pam_wrapper.c:1483)
==985738==    by 0x401723: setup_noconv (test_pam_wrapper.c:189)
==985738==    by 0x4889E82: ??? (in /usr/lib64/libcmocka.so.0.7.0)
==985738==    by 0x488A444: _cmocka_run_group_tests (in /usr/lib64/libcmocka.so.0.7.0)
==985738==    by 0x403EE5: main (test_pam_wrapper.c:1059)
=> Fix memory leaks with pam_start_confdir()

NEWS, modules/pam_env/pam_env.8.xml, modules/pam_env/pam_env.c
* modules/pam_env/pam_env.8.xml: Add the notice to the manual.
* modules/pam_env/pam_env.c (_pam_parse): Log deprecation warning
if debug enabled.
Or should the deprecation warning be there also without the debug arg?
=> pam_env: deprecation notice of reading the user environment

modules/pam_faillock/faillock.conf.5.xml, modules/pam_faillock/pam_faillock.c
=> faillock: Add a nodelay option

modules/pam_unix/support.c
The blank check could return 1 if root had empty password
because in the second case the password hash of root was used. We now
always return 0 in this case.
Fixes #284
* modules/pam_unix/support.c (_unix_blankpasswd): Make the loop
to cover the complete blank check so both existing and non existing
cases are identical except for the possible return value.
=> Second blank check with root for non-existent users must never return 1

modules/pam_unix/bigcrypt.c
If crypt_r() fails do not leak cdata.
Bug found with Muse.dev CI tool (specifically, the Infer static analyzer).  Muse's full results are [available](https://console.muse.dev/result/TomMD/linux-pam/01EQY5Q0JNQS8QPHRM5Z6EH7BK?search=bigc&tab=results) but if you are interested I could make a PR adding [the Muse CI configuration](https://github.com/TomMD/linux-pam/tree/master/.muse) to run Infer on each pull request and produce a github comment if there are any new bugs.
=> Fix memory leak that occurs in a rare situations

doc/man/pam.conf-syntax.xml
The done action does not terminate the stack processing in case
there is a failing module with bad action up in the stack.
* doc/man/pam.conf-syntax.xml: Clarify the effect of 'done'.
Fixes #307
=> Clarify the effect of 'done' in documentation

modules/pam_namespace/pam_namespace.c, modules/pam_selinux/pam_selinux.c
Check for the unlikely case [`string_to_security_class(3)`](https://manpages.debian.org/unstable/libselinux1-dev/string_to_security_class.3.en.html) does not find the
associated SELinux security class.
This will only happen if the loaded SELinux policy does not define the
class (which no sane policy does) or querying the selinuxfs
fails.
Suggested by #309
=> check for string_to_security_class failure 

configure.ac
I faced `test: too many arguments` when building Linux-PAM using [sbase](https://core.suckless.org/sbase/).
This is due to a non-POSIX syntax `test ... -a ...` and `test … -o …`.
> The XSI extensions specifying the -a and -o binary primaries and the '(' and ')' operators have been marked obsolescent.
https://pubs.opengroup.org/onlinepubs/9699919799/utilities/test.html
=> configure: test -a|o is not POSIX

modules/pam_setquota/pam_setquota.8.xml
I noticed some very minor errors in the pam_setquota.8 man-page, for example I somehow managed to mistype my own name in my mail address.
This PR fixes this, a missing . and some whitespace issues.
=> pam_setquota: Minor whitespace, spelling and mail address fixes

modules/pam_faillock/pam_faillock.c
Haven't done C in a long time, so I might need some help / CI checks with this :)
Fixes https://github.com/linux-pam/linux-pam/issues/322#issuecomment-764192605
=> Faillock: Use pluralization via dngettext or fallback

modules/pam_securetty/pam_securetty.c
Not shipping a config file should be perfectly valid for distros while
still having eg login pre-configured to honor securetty when present.
PAM itself doesn't ship any template either. So avoid spamming the log
file if /etc/securetty wasn't found.
=> pam_securetty: don't complain about missing config

configure.ac, modules/pam_faillock/faillock.c, modules/pam_namespace/Makefile.am
the default tallydir is "/var/run/faillock", and usually,
/var/run is mounted on tempfs. so faillock maybe not existed.
When we set flag to O_CREAT, and hope to create tallyfile,
but since the dir is not existed, open function will failed,
and faillock not works well. so fixed by when we want to create
tallyfile, and the dir is not existed, create it first.
Signed-off-by: Changqing Li <changqing.li@windriver.com>
=> faillock: create dir before create tally file

modules/pam_mkhomedir/mkhomedir_helper.8.xml, modules/pam_mkhomedir/mkhomedir_helper.c, modules/pam_mkhomedir/pam_mkhomedir.8.xml, modules/pam_mkhomedir/pam_mkhomedir.c
Follow the example of useradd(8) and set the file mode creation mask to
the value of UMASK configuration item from /etc/login.defs when umask=
option is not specified.
=> pam_mkhomedir: use UMASK from /etc/login.defs

modules/pam_faillock/main.c
convert spaces to tab for code style
refactor fragment of code to remove one macro
=> pam_faillock:

libpam_misc/misc_conv.c
Fixes #347
* libpam_misc/misc_conv.c (read_string): Use TCSAFLUSH instead
of TCSADRAIN when resetting the terminal echo state
=> misc_conv: Flush the terminal input after the password is read

modules/pam_userdb/pam_userdb.8.xml, modules/pam_userdb/pam_userdb.c
Recently, I debugged some problems stemming from the fact that `db_fetch` output in `.dptr` contained a non-printable character in the end and got passed directly to `crypt_r`. I tested this patch in RHEL-8, but I have no prior experience with pam. I'd be glad for a review.
Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=1791965
=> pam_userdb: Prevent garbage characters from db

doc/man/pam.conf-syntax.xml
Add short blurbs explaining that if a return code is not specified in
the "[value1=action1 value2=action2 ...]" form and "default=action" is
not specified, that return code's action defaults to "bad".
=> pam.conf: clarify default action for unspecified return codes

modules/pam_exec/pam_exec.8.xml, modules/pam_exec/pam_exec.c
Resolves: https://github.com/linux-pam/linux-pam/issues/334
I don't speak C. Please review with caution. This seemed like a reasonable simple copy/paste exercise since `quiet` has a very similar purpose to `quiet_log`.
Supersedes https://github.com/linux-pam/linux-pam/pull/335.
=> pam_exec: implement quiet_log option

modules/pam_unix/passverify.c
According to Zack Weinberg, the intended meaning of
CRYPT_SALT_METHOD_LEGACY is "passwd(1) should not use this hashing
method", it is not supposed to mean "force a password change on next
login for any user with an existing stored hash using this method".
This reverts commit 4da9febc39b955892a30686e8396785b96bb8ba5.
* modules/pam_unix/passverify.c (check_shadow_expiry)
[CRYPT_CHECKSALT_AVAILABLE]: Remove.
Closes: https://github.com/linux-pam/linux-pam/issues/367
=> pam_unix: do not use crypt_checksalt when checking for password expiration

Make.xml.rules.in, NEWS, ci/install-dependencies.sh, configure.ac, doc/custom-man.xsl, modules/pam_timestamp/Makefile.am, modules/pam_timestamp/hmac_openssl_wrapper.c, modules/pam_timestamp/hmac_openssl_wrapper.h, modules/pam_timestamp/pam_timestamp.8.xml, modules/pam_timestamp/pam_timestamp.c
sha1 is no longer recommended as a cryptographic algorithm for
authentication. Thus, the idea of this change is to replace the
implementation provided by hmacsha1 included in pam_timestamp module by
the one in the openssl library. This way, there's no need to maintain
the cryptographic algorithm implementation and it can be easily changed
with a single configuration change.
modules/pam_timestamp/hmac_openssl_wrapper.c: implement wrapper
functions around openssl's hmac implementation. Moreover, manage the key
generation and its read and write in a file. Include an option to
configure the cryptographic algorithm in login.defs file.
modules/pam_timestamp/hmac_openssl_wrapper.h: likewise.
modules/pam_timestamp/pam_timestamp.c: replace calls to functions
provided by hmacsha1 by functions …
=> pam_timestamp: replace hmac implementation

configure.ac, libpam_misc/misc_conv.c
The `libpam_misc:misc_conv()` password buffer is fixed at 512 bytes long.  This PR is two commits:
1. Add a `--with-misc-conv-bufsize` configure CLI option to allow setting the `misc_conv()` buffer size to an arbitrary value (e.g., 4096), but keep the default length at 512 bytes.
2. Change the default length of the `misc_conv()` buffer to 4096 bytes.
The PR is two commits just to show that the 2nd commit could be omitted if there would be problems increasing the default buffer length.
We have an internal use case to use Linux PAM for a cryptographic challenge/response login.  It looks something like this:
```
$ ssh someuser@somehost 
Challenge: ...a very long text blob...
Response: <wait for user input>
```
The user copies the challenge blob to an internal authorization system.  If the …
=> libpam_misc:misc_conv() buffer length

configure.ac, modules/pam_pwhistory/opasswd.c, modules/pam_unix/bigcrypt.c, modules/pam_unix/passverify.c, modules/pam_userdb/pam_userdb.c
Since many distributions are shipping a version of libxcrypt >= 4.0.0 as a replacement for glibc's libcrypt now, older versions of xcrypt, which could be installed in parallel, are not relevant anymore.
* configure.ac: Remove support for legacy xcrypt.
* ci/install-dependencies.sh: Likewise.
* modules/pam_cracklib/pam_cracklib.c: Likewise.
* modules/pam_pwhistory/opasswd.c: Likewise.
* modules/pam_unix/bigcrypt.c: Likewise.
* modules/pam_unix/passverify.c: Likewise.
* modules/pam_userdb/pam_userdb.c: Likewise.
=> Remove support for legacy xcrypt.

.gitignore, configure.ac, libpam/Makefile.am, libpam/pam.pc.in, libpam_misc/Makefile.am, libpam_misc/pam_misc.pc.in, libpamc/Makefile.am, libpamc/pamc.pc.in
This allow applications and PAM modules to automatically find libpam, libpam_misc and libpamc if they are installed instead of having to manually search for them.
I used the documentation at https://autotools.io/pkgconfig to know how to properly generate the files and looked at other projects to see how to have them be installed.
I didn't add a description to pamc.pc.in as I don't know what exactly this library does and didn't find the documentation for it.
=> Add pkgconfig files for libpam, libpam_misc and libpamc

configure.ac
Fix the following build failure with libxcrypt and uclibc-ng:
```
/srv/storage/autobuild/run/instance-0/output-1/host/opt/ext-toolchain/bin/../lib/gcc/arm-buildroot-linux-uclibcgnueabihf/9.3.0/../../../../arm-buildroot-linux-uclibcgnueabihf/bin/ld: unix_chkpwd-passverify.o: in function `verify_pwd_hash':
passverify.c:(.text+0xab4): undefined reference to `crypt_checksalt'
```
Fixes:
- http://autobuild.buildroot.org/results/65d68b7c9c7de1c7cb0f941ff9982f93a49a56f8
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
=> configure.ac: fix build with libxcrypt and uclibc-ng

modules/pam_unix/passverify.c
Remove the hard-coding of the idea that the only way pam_unix.so can
read the shadow file is if it can, in some way, run setuid-root.
Linux capabilities only require cap_dac_override to read the /etc/shadow
file.
This change achieves two things: it opens a path for a linux-pam
application to run without being setuid-root; further, it allows
unix_chkpwd to run non-setuid-root if it is installed:
sudo setcap cap_dac_override=ep unix_chkpwd
If we wanted to link against libcap, we could install this binary with
cap_dac_override=p, and use cap_set_proc() to raise the effective bit
at runtime. However, some distributions already link unix_chkpwd
against libcap-ng for some, likely spurious, reason so "ep" is fine
for now.
Signed-off-by: Andrew G. Morgan <morgan@kernel.org>
=> Permit unix_chkpwd & pam_unix.so to run without being setuid-root.

modules/pam_filter/pam_filter.c
Error: RESOURCE_LEAK (CWE-772): [#def26]
Linux-PAM-1.5.1/modules/pam_filter/pam_filter.c:356: open_fn: Returning handle opened by "open". [Note: The source code implementation of the function has been overridden by a user model.]
Linux-PAM-1.5.1/modules/pam_filter/pam_filter.c:356: var_assign: Assigning: "t" = handle returned from "open("/dev/tty", 2)".
Linux-PAM-1.5.1/modules/pam_filter/pam_filter.c:357: off_by_one: Testing whether handle "t" is strictly greater than zero is suspicious.  "t" leaks when it is zero.
Linux-PAM-1.5.1/modules/pam_filter/pam_filter.c:357: remediation: Did you intend to include equality with zero?
Linux-PAM-1.5.1/modules/pam_filter/pam_filter.c:367: leaked_handle: Handle variable "t" going out of scope leaks the handle.
365|   		pam_syslog(pamh, LOG_ERR,
366| …
=> pam_filter: fix resource leak

modules/pam_unix/passverify.c
The getspnam(3) manual page says that errno shall be set to EACCES when
the caller does not have permission to access the shadow password file.
Unfortunately, this contract is broken when libnss_systemd is used in
the nss stack.
Workaround this problem by falling back to the helper invocation when
pam_modutil_getspnam returns NULL regardless of errno.  As pam_unix
already behaves this way when selinux is enabled, it should be OK
for the case when selinux is not enabled, too.
* modules/pam_unix/passverify.c (get_account_info): When
pam_modutil_getspnam returns NULL, unconditionally fall back
to the helper invocation.
Complements: f220cace2053 ("Permit unix_chkpwd & pam_unix.so to run without being setuid-root")
Resolves: https://github.com/linux-pam/linux-pam/issues/379
=> pam_unix: workaround the problem caused by libnss_systemd

configure.ac
libxcrypt provides a libcrypt.pc file so use it if available as this will allow to retrieve the library path (e.g. `-L/home/buildroot/output/host//riscv64-buildroot-linux-musl/sysroot/usr/lib`) which is useful when cross-compiling and will avoid the following build failure on buildroot:
```
/home/buildroot/autobuild/run/instance-3/output-1/host/opt/ext-toolchain/bin/../lib/gcc/riscv64-buildroot-linux-musl/10.2.0/../../../../riscv64-buildroot-linux-musl/bin/ld: .libs/passverify.o: in function `.L30':
passverify.c:(.text+0x368): undefined reference to `crypt_checksalt'
```
Fixes:
- http://autobuild.buildroot.org/results/20b14e222b35c2d1269960075832b784ba81aa1a
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
=> configure.ac: also search libcrypt through pkg-config

doc/man/Makefile.am
pam_xauth_data.3.xml is missing in the source archive, so you cannot rebuild all manual pages.
=> Include pam_xauth_data.3.xml in source archive

configure.ac, doc/man/pam.8.xml
Compile in %vendordir%/pam.d section only if vendordir was enabled.
=> Only include vendordir in manual page if set

modules/pam_limits/pam_limits.8.xml, modules/pam_limits/pam_limits.c
pam_limits.so fails if it cannot read /etc/security/limits.conf. This is especially a problem if you use image based installations and updates (so image = /usr, not image = raw disk image). Use the vendor directory as fallback for a distribution provided default config.
=> Use vendor specific limits.conf as fallback

xtests/run-xtests.sh
Fixes:
```
mv: cannot stat '/etc/security/opasswd': No such file or directory
PASS: tst-pam_access1
mv: cannot stat '/etc/security/opasswd-pam-xtests': No such file or directory
==================
1 tests passed
0 tests not run
==================
```
Signed-off-by: Mingli Yu <mingli.yu@windriver.com>
=> run-xtests.sh: check whether files exist

modules/pam_faillock/main.c
`faillock` doesn't check the return value of `localtime` which might lead to a null pointer dereference and segfault when calling `strftime`. As the tally files are writable by the users in question, they can contain arbitrary data. As an example, to reproduce this you can try setting `tallies.records[i].time` to `0x8000000061dda477`.
=> Check the return value of localtime in faillock

modules/pam_limits/pam_limits.c
A config with only comments or an empty one is completely fine for
pam_limits. So don't complain about missing config files either.
=> pam_limits: don't fail on missing config files

modules/pam_rootok/pam_rootok.c
Do not report that the variable audit_fd is unused if HAVE_LIBAUDIT has not been defined.
=> pam_rooktok: fix build warning if HAVE_LIBAUDIT has not been defined

modules/pam_sepermit/Makefile.am, modules/pam_sepermit/pam_sepermit.c, modules/pam_sepermit/tst-pam_sepermit-retval.c
The parser of conf= option failed to recognize the option unless
it was specified without an argument, making it useless.
* modules/pam_sepermit/pam_sepermit.c: Include "pam_inline.h".
(pam_sm_authenticate): Fix parsing of conf= option.
* modules/pam_sepermit/tst-pam_sepermit-retval.c: New test.
* modules/pam_sepermit/Makefile.am (TESTS): Add $(check_PROGRAMS).
(check_PROGRAMS, tst_pam_sepermit_retval_LDADD): New variables.
Co-authored-by: Stefan Schubert <schubi@suse.de>
Resolves: https://github.com/linux-pam/linux-pam/pull/429
=> pam_sepermit: fix conf= option support

configure.ac, modules/pam_access/Makefile.am, modules/pam_access/pam_access.c, modules/pam_env/Makefile.am, modules/pam_env/pam_env.c, modules/pam_faillock/faillock.h, modules/pam_group/Makefile.am, modules/pam_group/pam_group.c, modules/pam_limits/Makefile.am, modules/pam_limits/pam_limits.c, modules/pam_namespace/Makefile.am, modules/pam_namespace/pam_namespace.h, modules/pam_pwhistory/opasswd.c, modules/pam_sepermit/Makefile.am, modules/pam_sepermit/pam_sepermit.c, modules/pam_time/Makefile.am, modules/pam_time/pam_time.c, modules/pam_unix/passverify.c, modules/pam_unix/passverify.h
Dmitry V. Levin (6):
Introduce SCONFIGDIR macro
modules: use SCONFIGDIR macro
pam_limits: make LIMITS_FILE_DIR macro consistent
modules: move SCONFIGDIR-based macro definitions from Makefile.am to the source code
Introduce VENDOR_SCONFIGDIR macro
pam_limits: use VENDOR_SCONFIGDIR macro
Assuming that we will have all PAM modules updated to support VENDORDIR,
introduce two macros to make the code more consistent.
Similar to VENDORDIR, SCONFIGDIR is a new macro defined to the
argument of --enable-sconfigdir option.  Unlike --enable-vendordir,
--enable-sconfigdir has a default value, so when --enable-sconfigdir
is not used for build, SCONFIGDIR will be defined to that default value.
Use SCONFIGDIR macro instead of open-coding "/etc/security",
the latter is not correct when configured using …
=> Introduce SCONFIGDIR and VENDOR_SCONFIGDIR macros

modules/pam_sepermit/pam_sepermit.8.xml, modules/pam_sepermit/pam_sepermit.c
Use the vendor directory (/usr/etc) as fallback for a distribution provided default config if there is no configuration in /etc.
* pam_sepermit.8.xml: add /usr/etc description
* pam_sepermit.c: Take care about the fallback configuration in /usr/etc.
=> pam_sepermit: use vendor specific sepermit.conf as fallback

modules/pam_faillock/faillock.h, modules/pam_faillock/pam_faillock.8.xml, modules/pam_faillock/pam_faillock.c
Use the vendor directory (/usr/etc) as fallback for a distribution provided default config if there is no configuration in /etc.
- pam_faillock.c, faillock.h : Take care about the fallback configuration in /usr/etc.
- pam_faillock.8.xml:  added /usr/etc description
=> pam_faillock: use vendor specific faillock.conf as fallback

modules/pam_pwhistory/opasswd.c, modules/pam_pwhistory/opasswd.h, modules/pam_pwhistory/pam_pwhistory.8.xml, modules/pam_pwhistory/pam_pwhistory.c, modules/pam_pwhistory/pwhistory_helper.c
Sometimes, especially in embedded devices, the /etc directory can be
read-only and/or not saved over upgrades. In order to ensure password
policies are maintained across upgrades and the module functions on
read-only file systems, allow the location of the password history file
to be set in the PAM configuration.
Signed-off-by: Edward <jinzhou.zhu1@ge.com>
[Martyn Welch: Updated commit message and ported to latest version]
Signed-off-by: Martyn Welch <martyn.welch@collabora.com>
=> pam_pwhistory: Enable alternate location for password history file

modules/pam_time/Makefile.am, modules/pam_time/pam_time.8.xml, modules/pam_time/pam_time.c, modules/pam_time/tst-pam_time-retval.c
Use the vendor directory as fallback for a distribution provided default config if there is no configuration in /etc.
* Makefile.am: compile testcases
* pam_time.8.xml: add description for vendor directory.
* pam_time.c: Take care about the fallback configuration in vendor directory.
* tst-pam_time-retval.c: General testcases for pam_time.
=> pam_time: use vendor specific time.conf as fallback

modules/pam_keyinit/pam_keyinit.c
modules/pam_keyinit/pam_keyinit.c: bypass setre*id() C library calls
with kernel calls and change global variables definitions to be
thread-safe.
configure.ac: macro definition for 32 bit system calls.
I also developed two test cases, but I decided to temporarily host them in [another repository](https://github.com/ikerexxe/test_pam_keyinit/blob/main/test_pam_keyinit.c). The tests would add new dependencies (cmoka, pamtest and pam_wrapper) and I think it's best if we agree on that first.
Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=1997969
=> pam_keyinit: thread-safe implementation

configure.ac, modules/pam_usertype/pam_usertype.8.xml, modules/pam_usertype/pam_usertype.c
modules/pam_usertype/pam_usertype.c: stop using SYS_UID_MIN to check if
it is a system account, because all accounts below the SYS_UID_MAX are
system users.
modules/pam_usertype/pam_usertype.8.xml: remove reference to SYS_UID_MIN
as it is no longer user to calculate the system accounts.
Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=1949137
=> pam_usertype: only use SYS_UID_MAX for system users

modules/pam_time/pam_time.c
Fixed warning: "Result of comparison against a string literal is unspecified
(use an explicit string comparison function instead)"
pam_time.c: Do not compare char * string with a constant.
=> module/pam_time: Fix clang compilation warning

modules/pam_exec/pam_exec.c
In the child process, freeing memory right before pam_syslog()
followed by _exit(ENOMEM) is useless.
* modules/pam_exec/pam_exec.c (call_exec): Do not call free(envlist).
Resolves: https://github.com/linux-pam/linux-pam/issues/444
=> pam_exec: remove redundant free() invocations

modules/pam_env/Makefile.am, modules/pam_env/tst-pam_env-retval.c
* modules/pam_env/tst-pam_env-retval.c: New file.
* modules/pam_env/Makefile.am (TESTS): Add $(check_PROGRAMS).
(check_PROGRAMS, tst_pam_env_retval_LDADD): New variables.
Co-authored-by: Dmitry V. Levin <ldv@altlinux.org>
=> pam_env: add a test of return values

modules/pam_env/pam_env.c
Move definitions of static functions before their first use
to avoid forward declarations cluttering the code.
=> pam_env: reorder definitions of static functions to avoid forward declarations

.github/workflows/ci.yml, ci/run-build-and-tests.sh
Given that we are adding more code that depends on --enable-vendordir, it's time to add a few vendordir enabled jobs to the test matrix.
=> ci: add a few vendordir enabled jobs

modules/pam_limits/pam_limits.8.xml, modules/pam_limits/pam_limits.c
Use the vendor directory as fallback for a distribution provided default config if there is no configuration in /etc.
- pam_limits.c: Take care about the fallback configuration in vendor directory.
- pam_limits.8.xml: Added description for vendor directory.
=> pam_limits: use vendor specific content in limits.d directory as fallback

modules/pam_namespace/namespace.conf.5.xml, modules/pam_namespace/pam_namespace.8.xml, modules/pam_namespace/pam_namespace.c, modules/pam_namespace/pam_namespace.h
Use the vendor directory as fallback for a distribution provided default config and scripts if there is no configuration in /etc.
pam_namespace.c: Take care about the fallback configuration in vendor directory.
pam_namespace.h: Defining vendor specific files and directories.
pam_namespace.8.xml: Added description for vendor directories and files.
namespace.conf.5.xml: Added description for vendor directories and files.
=> pam_namespace: use vendor specific namespace.conf and namespace.init as fallback

modules/pam_motd/pam_motd.c
…y, we wrongly relied on all filesystems providing a filetype. This fixes that by diverting to lstat() when we have no filetype.  To maintain MT safety, it wasn't possible to use lstat() in the scandir() filter function, so I have moved all of the filtering to an additional loop after scanning all the motd dirs.
I know I could do some initial filtering in the scandir(), but I find it better to keep the filtering in one place.
=> pam_motd: do not rely on all filesystems providing a filetype

libpam/pam_handlers.c
* libpam/pam_handlers.c (_pam_add_handler): Use calloc instead of malloc
for struct handler allocation to avoid returning garbage in some fields
of the structure on error path.
Resolves: https://github.com/linux-pam/linux-pam/issues/475
=> _pam_add_handler: make sure struct handler is properly initialized on error path

libpam/include/security/pam_modutil.h, modules/pam_pwhistory/Makefile.am, modules/pam_pwhistory/pam_pwhistory.8.xml, modules/pam_pwhistory/pam_pwhistory.c, modules/pam_pwhistory/pwhistory.conf, modules/pam_pwhistory/pwhistory.conf.5.xml, modules/pam_pwhistory/pwhistory_config.c, modules/pam_pwhistory/pwhistory_config.h
I have added a new `conf` option in pam_pwhistory to select the configuration file to read. The default one being `/etc/security/pwhistory.conf`. On top of that I have used `pam_modutil_search_key()` function to read the pwhistory configuration file. This configuration is then loaded in the corresponding `options` structure.
Besides, I have documented the new `conf` option and the configuration file itself.
Finally, I have improved the `pam_modutil_search_key()` documentation.
Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=2068461
=> pam_pwhistory: load config from file

modules/pam_lastlog/pam_lastlog.c
Check the return value of localtime_r() before calling strftime(). This function crashes if the argument is NULL.
Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=2012871
=> pam_lastlog: check localtime_r() return value

configure.ac, doc/.gitignore, doc/adg/Makefile.am, doc/custom-html.xsl.in, doc/custom-man.xsl.in, doc/mwg/Makefile.am, doc/sag/Makefile.am
Stylesheets are currently hardcoded. With this PR stylesheets can be defined while the confiure call.
configure.ac: Define new options to set variable stylesheets:
--enable-html-stylesheet=FILE
--enable-txt-stylesheet=FILE
--enable-pdf-stylesheet=FILE
--enable-man-stylesheet=FILE
doc/.gitignore: Ignoring files which will be build while running configure
doc/adg/Makefile.am: Using variable stylesheets
doc/mwg/Makefile.am: Using variable stylesheets
doc/sag/Makefile.am Using variable stylesheets
doc/custom-html.xsl → doc/custom-html.xsl.in: Template for configure able stylesheets. doc/custom-html.xsl will be genarted while the configure call.
doc/custom-man.xsl → doc/custom-man.xsl.in: Template for configure able stylesheets. doc/custom-man.xsl will be genarted while the configure call.
=> PAM: added configurable stylesheets

modules/pam_faillock/faillock.conf.5.xml, modules/pam_faillock/pam_faillock.8.xml
Adding note in man pages related to missing file post reboot
Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=2062512
=> pam_faillock: Clarify missing user faillock files after reboot 

modules/pam_faillock/pam_faillock.c
Resolve issue of consecutive failure msg for root if even_deny_root flag is not enabled.
Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=2082442
=> pam_faillock: Disable consecutive login failure message for root user 

modules/pam_env/pam_env.c
The quoteflg can become negative, creating an inconsistent behavior for quoted and unquoted empty string as explained in the issue #10. 
It shows an use case where length=0 and quoteflg=0, the condition `else if(quoteflg--){}` will not be validate but still decrement the flag to become <0. As a result, the condition at the next step will be validate.
Fix: #10 
Signed-off-by: Valentin Lefebvre <valentin.lefebvre@suse.com>
=> pam_env: _parse_line: fix quoteflg handled

doc/man/Makefile.am
The XMLS list of xml sources for the manual pages missed some xml files and instead contained some nroff sources.
=> doc/man/Makefile.am: fix XMLS list

configure.ac, modules/pam_shells/Makefile.am, modules/pam_shells/pam_shells.8.xml, modules/pam_shells/pam_shells.c
Use the vendor directory as fallback for a distribution provided default config if there is no one in /etc.
If pam will be compiled with the option --enable-vendordir=<vendor_dir> and NOT defined 
--disable-econf, the files which define valid login shells will be parsed in following order:
- <vendor_dir>/shells
- <vendor_dir>/shells.d/*
- /etc/shells.d/shells
But all files in <vendor_dir> will be ingnored if the user has defined his
own file /etc/shells.
This PR should solve: https://github.com/linux-pam/linux-pam/issues/498
- Makefile.am: Add libeconf setting.
- pam_shells.c: Take care about the fallback configuration in the vendor directory.
- pam_shells.8.xml: Added description for the vendor directory.
- configure.ac: Added ECONF settings for building man pages.
=> pam_shells: Use the vendor directory as fallback for a distribution provided default config if there is no one in /etc.

modules/pam_listfile/pam_listfile.c
pam module listfile assume the group being tested will be written at the end of the argument list by carrying only a pointer to the value being examined in `myval` to `apply_val`
Therefore example
```
auth    required       pam_listfile.so \
onerr=succeed apply=ftp item=user sense=deny file=/etc/ftpusers
```
modified from https://linux.die.net/man/8/pam_listfile is not working because `apply_val` will point to the latest value of `myval` which in this case will be `/etc/ftpusers` instead of `ftp`
This PR fixes this issue by copying the value of `myval` to `apply_val` instead of just taking a reference pointer
=> pam_listfile: fix pointer misuse leading to data corruption

.github/workflows/ci.yml, libpamc/include/security/pam_client.h, modules/pam_limits/pam_limits.c, modules/pam_unix/md5.c
This also silences all warnings reported by gcc-12 and clang-14.
=> Update for gcc-12 and clang-14

modules/pam_selinux/pam_selinux.c
security_getenforce(3) can return -1 on error; either because the selinuxfs is not mounted or reading from /sys/fs/selinux/enforce failed.
Since security_getenforce(3) is either called after an approving call to is_selinux_enabled(3) in create_context() or with populated module data in restore_context(), which requires a previous pass of create_context(), the selinuxfs should be mounted. Reading from /sys/fs/selinux/enforce should never fail (except being prohibited by the SElinux policy itself) since it is a public interface.
In the unlikely case of security_getenforce(3) nevertheless failing continue execution as if the result was enforcing (likewise to pam_sepermit and pam_rootok).
=> pam_selinux: treat getenforce failures as enforcing

libpam/pam_dynamic.c
Apparently, the PAM_SHL variant cannot be compiled since the very first commit back in 2005 when it was introduced, and another variant uses PAM_DYLD which is virtually unknown to search engines.
* libpam/pam_dynamic.c [PAM_SHL || PAM_DYLD]: Remove.
Resolves: https://github.com/linux-pam/linux-pam/issues/477
=> libpam: remove dead code in pam_dynamic.c

modules/pam_pwhistory/Makefile.am, modules/pam_pwhistory/pam_pwhistory.8.xml, modules/pam_pwhistory/pwhistory_config.c, modules/pam_pwhistory/tst-pam_pwhistory-retval.c
Use the vendor directory defined by --enable-vendordir=DIR configure option as fallback for the distribution provided default config file if there is no configuration in /etc.
* modules/pam_pwhistory/pam_pwhistory.8.xml: Describes pwhistory.conf
* modules/pam_pwhistory/pwhistory_config.c: (parse_config_file) [VENDOR_PWHISTORY_DEFAULT_CONF] Try to open
VENDOR_PWHISTORY_DEFAULT_CONF if PWHISTORY_DEFAULT_CONF file does not exist.
* modules/pam_pwhistory/tst-pam_pwhistory-retval.c: testcase for pam_pwhistory.
* modules/pam_pwhistory/Makefile.am: define testcase
=> pam_pwhistory: use vendor specific pwhistory.conf as fallback

configure.ac, modules/pam_unix/Makefile.am, modules/pam_unix/pam_unix_passwd.c
The yppasswd_xdr functions are not used if NIS is disabled, so don't link against that object file.
* configure.ac: define HAVE_NIS if NIS is enabled
* modules/pam_unix/Makefile.am: don't link against yppasswd_xdr.c if NIS is disabled
* modules/pam_unix/pam_unix_passwd.c: don't redefine HAVE_NIS
=> pam_unix: don't link against yppasswd_xdr if NIS is disabled (#523)

libpam/pam_modutil_getlogin.c
utmp uses 32bit time_t for compatibility with 32bit userland on some
64bit systems and is thus not Y2038 safe. Use getlogin() from libc
which avoids using utmp.
* libpam/pam_modutil_getlogin.c: Use getlogin() instead of parsing utmp
=> libpam: use getlogin() from libc and not utmp

ci/run-build-and-tests.sh, configure.ac
pam_lastlog uses utmp, wtmp, btmp and lastlog. None of them is Y2038 safe, even on 64bit architectures. Most 64bit architectures uses 32bit time_t for compat reasons with 32bit userland.
Additional, all relevant tools for which pam_lastlog would make sense have already own support for all four files, so this module will most likely only create duplicate entries.
* configure.ac: don't build pam_lastlog by default.
=> pam_lastlog: deprecate it and disable by default

doc/man/pam.8.xml, doc/man/pam.conf-desc.xml, doc/man/pam.conf-dir.xml, doc/man/pam.conf.5.xml
Make /usr/lib/pam.d and <vendordir>/pam.d more visible in the standard manual pages, so that people don't assume there is only /etc/pam.d
* doc/man/pam.8.xml: Don't always speak about /etc/pam.d only
* doc/man/pam.conf-desc.xml: Don't always speak about /etc/pam.d only
* doc/man/pam.conf-dir.xml: Explain search path for pam config files
* doc/man/pam.conf.5.xml: Add filelist with all pam.d directories
=> manual pages: enhance pam.d documentation

configure.ac, modules/pam_issue/Makefile.am, modules/pam_issue/pam_issue.c, modules/pam_timestamp/Makefile.am, modules/pam_timestamp/pam_timestamp.c
The struct utmp from glibc uses on many 64bit architectures a 32bit time_t for compatibility with a 32bit userland, which means utmp will not survive the year 2038 (32bit time_t overflow). Use the data from logind instead of utmp.
* configure.ac: Add option --enable-logind
* modules/pam_issue/Makefile.am: Add CFLAGS/LIBS for logind support
* modules/pam_issue/pam_issue.c: Use sd_get_sessions instead of utmp
* modules/pam_timestamp/Makefile.am: Add CFLAGS/LIBS for logind support
* modules/pam_timestamp/pam_timestamp.c: query logind for login time
=> Y2038: use logind instead of utmp

doc/man/pam_item_types_std.inc.xml
man/pam_item_types_std.inc.xml: in the past PAM_TTY was used for tty devices and $DISPLAY variables for X-based applications. With the introduction of PAM_DISPLAY PAM_TTY should only be used for devices.
=> documentation: document usage of $DISPLAY and PAM_TTY

modules/pam_timestamp/hmac_openssl_wrapper.c
bcba17939e1b1a568cd4a764534cde74d37078cc started using pam_overwrite_n() without providing the definition to this function, which causes a build failure.
modules/pam_timestamp/hmac_openssl_wrapper.c: include pam_inline.h
=> pam_timestamp: fix build failure

configure.ac, modules/pam_unix/pam_unix_passwd.c, modules/pam_unix/support.c
modules/pam_unix/yppasswd_xdr.c: Include config.h and don't compile the XDR functions until HAVE_NIS is set
=> pam_unix: fix compiling if HAVE_NIS is not set

modules/pam_env/pam_env.conf.5.xml
Hi,
I fixed a grammar mistake in `pam_env.conf.5`.
=> doc: fix a grammar mistake

.github/workflows/ci.yml, Make.xml.rules.in, ci/run-build-and-tests.sh, configure.ac, modules/pam_timestamp/Makefile.am
Added --enable-openssl build and fixed regarding issues around --stringparam profile.condition settings.
.github/workflows/ci.yml: added openssl builds
Make.xml.rules.in: fixed double profile.condition settings
configure.ac: fixed double profile.condition settings
ci/run-build-and-tests.sh: added openssl builds
This should solve issue:
https://github.com/linux-pam/linux-pam/issues/553
=> build: fix --enable-openssl support

modules/pam_succeed_if/pam_succeed_if.c
* modules/pam_succeed_if/pam_succeed_if.c (evaluate): Do not use the result of keyword substitution for keyword match.
Resolves: https://github.com/linux-pam/linux-pam/issues/560
=> pam_succeed_if: do not use the result of keyword substitution for keyword match

modules/pam_limits/pam_limits.c, modules/pam_namespace/pam_namespace.h
GCC and Clang only define the macro `linux` when using the GNU dialect of C (e.g. -std=gnu11 instead of -std=c11).  Since `linux` is also not in a reserved namespace it might be target of collisions. Use the canonical macro `__linux__` instead (already used in pam_limits.c).
=> modules: update Linux detection

libpam/include/test_assert.h, modules/pam_pwhistory/opasswd.c, modules/pam_timestamp/pam_timestamp.c, tests/tst-dlopen.c
`PATH_MAX` is optional in POSIX, and not defined on GNU/Hurd; hence, do some changes to be able to build PAM more on Hurd:
- pam_timestamp: check for its existence before trying to check it
- pam_pwhistory: use `asprintf()` to allocate buffers
- tests: define a fallback `PATH_MAX` if not available
=> Various PATH_MAX fixes

modules/pam_nologin/pam_nologin.c
On some systems (e.g. GNU/Hurd), `read()` succeeds on the fd of a directory; since the module assumes that `read()` fails (and thus `pam_modutil_read()` as well), manually fail in case the open fd refers to a directory.
=> pam_nologin: explicitly fail when nologin path is a directory

Makefile.am, configure.ac
Allow the user to not build the examples through `--disable-examples` (enabled by default); this can be useful:
- when cross-compiling, as the examples are not useful
- in distribution builds, not building stuff that is not used in any way
=> configure.ac: add `--enable-examples` option

examples/tty_conv.c
termio.h is the old System V version of the interface header, and is only provided in glibc and dietlibc as far as I can tell. This fixes it to instead use the POSIX termios.h.
=> examples/tty_conv: fix build failure on musl

modules/pam_shells/pam_shells.8.xml, modules/pam_shells/pam_shells.c
Until before, in this case PAM_AUTH_ERR was returned. This leads to unknown users being logged with the unknown username.
Now it resembles the behavior of other modules like pam_unix in this case.
see #483
=> pam_shells: return PAM_USER_UNKNOWN if getpwnam fails

modules/pam_shells/pam_shells.c
The same leak occurs in shadow and util-linux:
- https://github.com/shadow-maint/shadow/pull/732
- https://github.com/util-linux/util-linux/pull/2239
=> pam_shells: Plug econf memory leak

modules/pam_pwhistory/opasswd.c
retval was being defined only in #ifdef HAVE_CRYPT_R, but used unconditionally.
=> Fix build if crypt_r isn't available

.github/workflows/ci.yml
* .github/workflows/ci.yml (gcc13-x86_64, clang15-x86_64): New jobs.
(gcc12-x86_64-vendordir): Rename to gcc13-x86_64-vendordir, replace gcc-12 with gcc-13.
(gcc12-x86_64-openssl): Rename to gcc13-x86_64-openssl, replace gcc-12 with gcc-13.
(clang14-x86_64-vendordir): Rename to clang15-x86_64-vendordir, replace clang-14 with clang-15.
(clang14-x86_64-openssl): Rename to clang15-x86_64-openssl, replace clang-14 with clang-15.
=> .github: add gcc-13 and clang-15 jobs

modules/pam_unix/support.c
This change improves the fallback values for the "rounds" parameter for yescrypt and blowfish by using the smallest reasonable value if the users sets a too low value and by using the highest reasonable value if the user sets a too high value. This better realizes user intent and is consistent with the approach taken for SHA256.
=> pam_unix: improve fallback values for "rounds" for yescrypt and blowfish

modules/pam_access/access.conf, modules/pam_access/access.conf.5.xml
* modules/pam_access/access.conf.5.xml: Add example and note for IPv6 link-local addresses
* modules/pam_access/access.conf: Add example for IPv6 link-local addresses
=> pam_access: document IPv6 link-local addresses (#582)

modules/pam_faillock/pam_faillock.c, modules/pam_selinux/pam_selinux.c
Pam_faillock uses audit_log_user_message to write to the audit system. It does not take an op argument, so you have to add one yourself. Otherwise the pam_faillock part of the message is lost because it's not in key=value format.
Also, we can't use uid in that event because the kernel already adds that field. What we normally do is use 'suid' (meaning sender uid) as the field name.
=> Fix up formatting of audit messages

.github/workflows/ci.yml, libpam/pam_start.c, modules/pam_faillock/tst-pam_faillock-retval.c, tests/tst-pam_fail_delay.c, tests/tst-pam_getenvlist.c, tests/tst-pam_mkargv.c, tests/tst-pam_start.c, tests/tst-pam_start_confdir.c
* tests: free handles via pam_end()
Destroy the pam handles via pam_end() to release all associated resources.  This allows to run the test-suite with sanitizers and validates the resource cleanup in pam_end() and callees.
* pam_start: free handlers on handler init failure
If the pam handlers fail to initialize halfway, clean them up afterwards.  Since we set the handle to NULL callers can't clean them.
* pam_faillock: free handle in test
* ci: add GCC 13 job with sanitzers
=> Remove memory leaks in tests

conf/pam_conv1/pam_conv_y.y, libpam/pam_item.c, libpam/pam_misc.c, libpam/pam_modutil_searchkey.c, libpam/pam_start.c, libpamc/pamc_load.c, modules/pam_access/pam_access.c, modules/pam_env/pam_env.c, modules/pam_faillock/faillock_config.c, modules/pam_filter/upperLOWER/upperLOWER.c, modules/pam_group/pam_group.c, modules/pam_lastlog/pam_lastlog.c, modules/pam_limits/pam_limits.c, modules/pam_namespace/argv_parse.c, modules/pam_namespace/pam_namespace.c, modules/pam_pwhistory/opasswd.c, modules/pam_securetty/pam_securetty.c, modules/pam_sepermit/pam_sepermit.c, modules/pam_time/pam_time.c, modules/pam_unix/support.c, modules/pam_usertype/pam_usertype.c
Character handling functions, like isspace(3), expect a value representable as unsigned char or equal to EOF.
Otherwise the behavior is undefined.
See https://wiki.sei.cmu.edu/confluence/display/c/STR37-C.+Arguments+to+character-handling+functions+must+be+representable+as+an+unsigned+char
=> cast to unsigned char for character handling function

libpam/include/security/_pam_macros.h, modules/pam_timestamp/sha1.c
* pam_timestamp: constify sha1 padding block
The padding block is only read from via memcpy(3).
* pam_timestamp: use secure memory erasure
Closes: https://github.com/linux-pam/linux-pam/issues/575
* libpam: avoid reserved variable names in macros
Identifiers staring with an underscores are reserved by the C standard.
Also avoid double underscore, which are reserved by C++, in header file.
=> Memory erasure followups

modules/pam_pwhistory/pam_pwhistory.c, modules/pam_pwhistory/pwhistory_helper.c
This bug was observed in an environment where SELinux was enabled and no file override was passed to `pam_pwhistory.so` in pam config. That causes a `NULL` value to be passed as an argument when calling `pwhistory_helper` binary, short-circuiting the arguments to just three.
The changes introduced handle the default case when the file is not overridden and passed as an empty string rather than a `NULL` value so that `pwhistory_helper` binary when called via `execve` can read all the arguments passed.
=> pam_pwhistory: fix passing NULL filename argument to pwhistory helper

libpam/pam_env.c
pam_putenv and pam_getenv do not properly handle strings which are longer than 2 GB (INT_MAX).
In pam_putenv the l2eq variable could overflow and turn negative, leading to out of boundary access (after the fact that signed integer overflow is undefined behavior).
In pam_getenv a very long string could lead to a small int value so other environment variables could match.
The easiest fix for both is to use size_t.
Proof of Concept (compile with `-fsanitize=address`):
```
#include <security/pam_misc.h>
#include <stdio.h>
#include <unistd.h>
misc_conv,
NULL
};
pam_handle_t *pamh = NULL;
int ret;
char *val;
ret = pam_start("poc", "poc", …
```
=> pam_env: fix handling of huge strings

configure.ac, libpam/pam_modutil_sanitize.c
* configure.ac: check whether close_range() is available in the system.
* libpam/pam_modutil_sanitize.c: use close_range() to close all file descriptors. If the interface isn't available use the previous approach.
Link: https://github.com/linux-pam/linux-pam/pull/276
Resolves: https://issues.redhat.com/browse/RHEL-5099
=> libpam: use close_range() to close file descriptors

libpam/pam_misc.c
It is possible to trigger an integer overflow in _pam_strdup if the passed string is longer than INT_MAX, which could lead to a smaller memory allocation than needed for the strcpy call.
This in turn could lead to a heap overflow.
Proof of Concept (64 bit system with enough RAM, i.e. more than 4 GB):
```
#include <stdint.h>
static int
test_conv (int num_msg, const struct pam_message **msgm,
struct pam_response **response, void *appdata_ptr) {
return 0;
}
test_conv,
NULL
};
pam_handle_t *pamh;
char *p;
/* create a string which returns UINT_MAX when called with strlen */
if ((p = malloc((size_t)UINT_MAX + 1)) == NULL)
err(1, "malloc"); …
```
=> libpam: fix possible heap overflow in _pam_strdup

libpam/pam_env.c
The debug output of environment variables tries to properly format pointers in a right-aligned way. 9 characters are not enough for 32 bit pointers though due to prepended 0x. Also, it takes 18 for 64 bit systems.
Adjust the formatter properly for architectures.
32 bit before:
```
[../../libpam/pam_env.c:_pam_dump_env(32)] environment entries used = 2 [of 10 allocated]
>0   [0xf55005d0]:[a=b]
>1   [    (nil)]:[(null)]
*NOTE* the last item should be (nil)
```
32 bit after:
```
[../../libpam/pam_env.c:_pam_dump_env(33)] environment entries used = 2 [of 10 allocated]
>0   [0xf54005d0]:[a=b]
>1   [     (nil)]:[(null)]
*NOTE* the last item should be (nil)
```
64 bit before:
```
[../../libpam/pam_env.c:_pam_dump_env(32)] environment entries used = 2 [of 10 allocated]
>0   [0x6020000001d0]:[a=b] …
```
=> libpam: improve debug output

libpam/pam_handlers.c
An endless loop with fgets can be triggered if exactly one free byte is left in buffer, because fgets will fill this byte with \0 without reading any further data from file.
This requires an invalid system configuration.
1. Create a configuration file with excessively long line
`python -c 'print("a" + " " * 1021 + "\\ suffix")' > /tmp/poc`
2. Run proof of concept
```
#include <stdint.h>
static int
test_conv (int num_msg, const struct pam_message **msgm,
struct pam_response **response, void *appdata_ptr) {
return 0;
}
test_conv,
NULL
};
pam_handle_t *pamh;
pam_start_confdir("poc", "nobody", &conv, "/tmp", &pamh); …
```
=> libpam: avoid endless loop on long config line

libpam/pam_handlers.c
If a configuration file contains lines which are longer than 1024 characters, _pam_assemble_line splits them into multiple ones.
This may lead to comments being interpreted as actual configuration lines.
1. Create a configuration line with a very long comment
`python -c 'print("a" + " " * 1030 + "just a comment")' > /tmp/poc`
2. Run Proof of Concept with --enable-debug compiled libpam
```
#include <stdint.h>
static int
test_conv (int num_msg, const struct pam_message **msgm,
struct pam_response **response, void *appdata_ptr) {
return 0;
}
test_conv,
NULL
};
pam_handle_t *pamh;
pam_start_confdir("poc", "nobody", …
```
=> libpam: stop processing excessively long lines

modules/pam_rootok/pam_rootok.c
The amount of va_start and va_end calls should be identical. Since va_end is called right after vasprintf, don't call it later again.
=> pam_rootok: call va_end only once

libpam/pam_auth.c, libpam/pam_env.c, libpam/pam_handlers.c, libpam/pam_item.c, libpam/pam_misc.c, modules/pam_env/pam_env.c, modules/pam_time/pam_time.c
The D macro already adds function names as prefix to the message. It is not needed to do it manually again.
Also fixed two typos in debug messages.
=> Improve debug messages

libpam/pam_account.c, libpam/pam_auth.c, libpam/pam_data.c, libpam/pam_delay.c, libpam/pam_dispatch.c, libpam/pam_end.c, libpam/pam_env.c, libpam/pam_handlers.c, libpam/pam_item.c, libpam/pam_password.c, libpam/pam_private.h, libpam/pam_session.c
The first argument of IF_NO_PAMH is supposed to be the name of the function which was called with pamh being NULL.
With `__FUNCTION__` the name can be inserted automatically by the compiler which is also already done with D macro.
Fixes a bug in which _pam_drop_env erroneously logs with the function name _pam_make_env.
=> libpam: simplify IF_NO_PAMH

libpam/pam_env.c, libpam/pam_item.c, libpam_misc/misc_conv.c, modules/pam_filter/pam_filter.c, modules/pam_group/pam_group.c, modules/pam_listfile/pam_listfile.c, modules/pam_namespace/pam_namespace.c, modules/pam_time/pam_time.c, modules/pam_timestamp/hmac_openssl_wrapper.c, modules/pam_unix/support.c
It is not required to cast the results of calloc, malloc, realloc, etc.
=> treewide: do not cast calloc/malloc/realloc

libpam/pam_misc.c
It is possible to trigger a signed integer overflow when parsing jump numbers for pam return types.
Fail if the number becomes too large.
Proof of Concept (compile with -fsanitize=undefined):
1. Create invalid /tmp/poc
```
echo "auth success=111111111111111111111111" > /tmp/po
```
2. Run Proof of Concept
```
#include <stdint.h>
static int
test_conv (int num_msg, const struct pam_message **msgm,
struct pam_response **response, void *appdata_ptr) {
return 0;
}
test_conv,
NULL
};
pam_handle_t *pamh;
pam_start_confdir("poc", "nobody", &conv, "/tmp", &pamh);
return 0;
}
```
Output is:
```
../../libpam/pam_misc.c:332:7: runtime error: …
```
=> libpam: fix integer overflow when parsing configs

libpam/pam_handlers.c
The argument vector for a module is created in _pam_parse_conf_file, which is performed by _pam_mkargv. If memory allocation fails in _pam_mkargv, then an empty argv is returned. This has to be checked by the caller to not silently drop arguments requested by configuration.
=> libpam: drop module if memory allocation failed

modules/pam_echo/pam_echo.c
The module might overflow heap on 32 bit systems if a 4 GB file is supplied as argument.
I have used the size limit which is also in place for pam_motd already.
Proof of Concept (on a 32 bit system):
1. Create a 4 GB file
```
dd if=/dev/zero of=/tmp/huge bs=1 count=1 seek=4294967295
```
2. Create a PAM configuration with pam_echo
```
session                optional        pam_echo.so file=/tmp/huge
```
3. Use the PAM tool, e.g. su (if the line is added to your su configuration)
=> pam_echo: avoid heap overflow on huge files

modules/pam_exec/pam_exec.c, modules/pam_securetty/pam_securetty.c
If an executed program prints \0 at the beginning of a line, then pam_exec triggers an out of boundary read (and possible) write on the stack.
Proof of Concept (compile with -fsanitize=address):
```
auth optional pam_exec.so stdout /bin/echo -ne \x00
```
=> pam_exec: fix stack overflow on \0 output

modules/pam_shells/pam_shells.c
- Only allow absolute paths for login shells
- Handle truncated lines
- Use getusershell if available (dropped after @ldv-alt pointed out possible MT issues)
Some distributions have comments in /etc/shells. These should never be considered valid login shells.
See also https://github.com/shadow-maint/shadow/pull/837 in shadow.
=> pam_shells: improve /etc/shells handling

libpam/pam_handlers.c
When there's a loop of configuration files consisting solely of includes the recursion depth level is never incremented and thus no upper limit is enforced. This leads to a crash caused by a stack overflow.
This patch updates the logic to track both the number of includes as well as the number of substacks we are on; ultimately adding a new parameter to track this information.
=> libpam: avoid infinite recursion with includes

libpam/pam_misc.c
* libpam/pam_misc.c (_pam_mkargv): Return 0 in case of memory allocation failure.
=> libpam: fix _pam_mkargv return value on error path

configure.ac, doc/sag/Linux-PAM_SAG.xml, doc/sag/pam_canonicalize_user.xml, modules/Makefile.am, modules/pam_canonicalize_user/Makefile.am, modules/pam_canonicalize_user/README.xml, modules/pam_canonicalize_user/pam_canonicalize_user.8.xml, modules/pam_canonicalize_user/pam_canonicalize_user.c, modules/pam_canonicalize_user/tst-pam_canonicalize_user, modules/pam_canonicalize_user/tst-pam_canonicalize_user-retval.c
This module uses the name of the user obtained via pam_get_user(3)
as a key to query the password database, and replaces PAM_USER
with the pw_name value that has been returned.
The main usage scenario is systems where a user name is used in several
distinct authentication systems, some of them being case sensitive while
others are not.
The issue this module deals with pops up from time to time.
For example, 9 years ago a similar user name canonicalization was implemented in pam_selinux:
https://bugzilla.redhat.com/show_bug.cgi?id=1071010
https://github.com/linux-pam/linux-pam/commit/da695db7a453b1e2a5ef63fcca21d59a2ed75dda
https://lists.fedorahosted.org/pipermail/pam-developers/2014-March/thread.html
=> pam_canonicalize_user: new module to canonicalize user name

modules/pam_unix/support.c
Retrieves `YESCRYPT_COST_FACTOR` from `/etc/login.defs` for Yescrypt, in a similar fashion to reading the number of rounds for SHA-2.
Resolves #607.
=> pam_unix: read yescrypt rounds from login.defs

modules/pam_setquota/pam_setquota.c
The result of pam_modutil_search_key must be freed.
I have checked other pam_modutil_search_key callers and was unable to find other occurrences of memory leaks.
Proof of Concept (compiled with -fsanitize=address):
1. In /etc/pam.d/su:
```
session  required   pam_setquota.so
```
2. In /etc/login.defs:
```
UID_MIN                  1000
```
3. Run a successful su session and exit again
You should be able to see something like:
```
=================================================================
==63378==ERROR: LeakSanitizer: detected memory leaks
Direct leak of 5 byte(s) in 1 object(s) allocated from:
#0 0x7fd88766d718 in __interceptor_strdup ../../../../libsanitizer/asan/asan_interceptors.cpp:454
#1 0x7fd8873f815d in pam_modutil_search_key (/usr/lib/libpam.so.0+0x8b15d)
#2 0x7fd886292e55 …
```
=> pam_setquota: plug memory leak

libpam_misc/misc_conv.c
Technically it's identical on pretty much all available systems, but let's follow C specifications.
=> libpam_misc: use sig_atomic_t instead of int

libpam/pam_handlers.c, libpam/pam_misc.c, libpam/pam_private.h
I have split this PR into multiple commits for easier review. Feel free to squash!
The format argument to _pam_StrTok is always the same and the function is not exposed through API, which means that it can be easily adjusted. It uses a table internally to support variable formats. But since the format is always the same, it can just use strspn/strcspn.
Due to this, I have renamed the function to _pam_tokenize so nobody expects strtok-like arguments.
=> libpam: simplify _pam_StrTok

libpam/pam_modutil_check_user.c, modules/pam_localuser/tst-pam_localuser-retval.c
This already implies that the passwd file itself is broken. Yet do not skip lines by accident due to fgets limitations.
As a positive side effect, arbitrarily long lines and user names are supported now as well.
=> libpam: treat NUL in passwd files correctly

modules/pam_unix/support.c
It is possible to trigger an out of boundary read with very long usernames (strlen's result is stored in an int) or, with even longer usernames, match other users with same prefix. This would mean that roott[and lots of t's following] could match root user.
Also do not allow ':' in names when iterating through the passwd file this way.
With help of joern, @ellcs spotted one of the int assignments of strlen's return value. @BenBE noticed that the module can be reached from pam_start.
Please note though that this PoC only works if `pam_chauthtok` is called directly after `pam_start`, which popular tools do not do. Even the ones you could get into this code path have limitations on user names which makes this more theoretical than it might look at first.
Proof of Concept for OOB access …
=> pam_unix: handle invalid names in _unix_getpwnam

modules/pam_shells/pam_shells.c
The \n at the end of a line has to be removed, otherwise the strcmp check will always fail.
Regression introduced in f800c5a8533003be7df56e6253821cf145f1a725.
Not part of any release.
=> pam_shells: fix regression (no release)

configure.ac, libpam/pam_modutil_searchkey.c, modules/pam_pwhistory/opasswd.c, modules/pam_shells/pam_shells.c
Apparently, getline is being used unconditionally in pam_namespace and pam_sepermit.  In pam_namespace, it is being used since 2006 when the module was introduced in the first place.
Let's assume getline is universally available and let's use it unconditionally in other cases, too.
* configure.ac (AC_CHECK_FUNCS): Remove getline and getdelim.
* libpam/pam_modutil_searchkey.c (pam_modutil_search_key): Use getline unconditionally.
* modules/pam_pwhistory/opasswd.c (check_old_pass, save_old_pass): Likewise.
* modules/pam_shells/pam_shells.c (perform_check): Likewise.
=> Assume getline exists

modules/pam_unix/passverify.c
The combination of snprintf and fputs is not needed. It is possible to call fprintf directly. The previously ignored return value of snprintf is covered this way as well.
This also simplifies transition from fgets to getline later on.
=> pam_unix: simplify save_old_password

modules/pam_xauth/pam_xauth.c
The strcspn function can easily replace memchr here. The latter would scan the entire buffer and requires a manual size limitation.
This in turn also simplifies an fgets to getline transition.
=> pam_xauth: simplify check_acl

modules/pam_unix/passverify.c
The shadow library uses "greater than or equal to" checks instead of current "greater than" checks in pam_unix.
The account expiry check is already "greater than or equal to" so this adjustment can even be argued without making references to other projects.
This is no regression with my last integer overflow adjustments (checked twice). At first I thought that it might even make sense to adjust shadow code instead, but a scenario with max age and inactive being set to 0 (pretty much a one time password setup) could not be reproduced in current pam_unix.so code. Also the "greater than or equal to" checks can be found in OpenBSD's auth_check_expire code.
References:
https://github.com/shadow-maint/shadow/blob/master/lib/isexpired.c#L55 …
=> pam_unix: sync expiry checks with shadow

doc/specs/parse_y.y, libpam/include/security/_pam_macros.h, libpam/pam_modutil_cleanup.c, libpam/pam_modutil_getgrgid.c, libpam/pam_modutil_getgrnam.c, libpam/pam_modutil_getpwnam.c, libpam/pam_modutil_getpwuid.c, libpam/pam_modutil_getspnam.c, libpamc/pamc_load.c, libpamc/test/modules/pam_secret.c, modules/pam_filter/pam_filter.c, modules/pam_listfile/pam_listfile.c, modules/pam_namespace/argv_parse.c, modules/pam_stress/pam_stress.c, modules/pam_timestamp/hmac_openssl_wrapper.c, modules/pam_unix/pam_unix_auth.c, modules/pam_xauth/pam_xauth.c
The C standard guarantees that if the argument of free() is a null pointer, no action occurs.
=> treewide: assume free(NULL) is no-op

libpam/pam_misc.c, libpamc/pamc_load.c, modules/pam_access/pam_access.c, modules/pam_debug/pam_debug.c, modules/pam_namespace/pam_namespace.c, modules/pam_unix/support.c
Very long strings could overflow the int data type. Make sure to use the correct data type.
Spotted and fixed with @BenBE and @Maaxxs based on discovery by @ellcs.
This is also a preparation for transition from fgets to getline in pam_access.
=> treewide: store strlen results in size_t

conf/pam_conv1/pam_conv_l.l, conf/pam_conv1/pam_conv_y.y
Fix various issues in the pam_conv1 tool, which is not installed by default:
- Show correct line number in output
- Fix memory leak of service name (-fsanitize=address shows leakage)
- Check strdup return values
- Avoid undefined behavior with input files having a lot of lines
- Use return instead of exit in main to support stack protector of main function
Spotted by @BenBE and fixed together.
Proof of Concept (signed overflow of input lines):
```
$ dd if=/dev/zero bs=1024 count=4194305 | tr '\0' '\n' > pam.conf
$ pam_conv1 < pam.conf
../../../conf/pam_conv1/pam_conv_l.l:43:5: runtime error: signed integer overflow: 2147483647 + 1 cannot be represented in type 'int'
```
Proof of Concept (line number output):
```
$ echo -n "su auth required pam_filter.so run1 filter " > pam.conf
$ …
```
=> conf/pam_conv1: fix memory and integer handling

modules/pam_namespace/argv_parse.c
If a lot of arguments are found in a namespace.conf file, argc might overflow, which is an undefined behavior.
In most cases, the realloc will instantly fail due to a wrap around.
Protect properly by avoiding the calculation in the first place.
=> pam_namespace: handle huge namespace.conf lines

libpam/pam_auth.c, libpam/pam_end.c, libpam/pam_misc.c, libpam/pam_password.c, libpam/pam_start.c
The D macro itself already adds the function names.
It is a follow up to 79f97b5dfddbd54942036851e49c369502689853.
=> libpam: remove function prefixes in debug messages

doc/man/pam.3.xml, doc/man/pam_open_session.3.xml, libpam/pam_delay.c, libpam/pam_dispatch.c, libpam/pam_password.c, libpam/pam_private.h, libpam_misc/misc_conv.c, libpamc/pamc_load.c, libpamc/test/agents/secret@here, libpamc/test/modules/pam_secret.c, modules/pam_access/pam_access.c, modules/pam_env/pam_env.8.xml, modules/pam_limits/pam_limits.c, modules/pam_namespace/pam_namespace.c, modules/pam_pwhistory/opasswd.c, modules/pam_unix/md5_crypt.c, modules/pam_unix/pam_unix_auth.c, modules/pam_unix/pam_unix_passwd.c, modules/pam_unix/support.c
Spotted during review and with the tool `codespell`.
=> treewide: fix typos in comments and documentation

modules/pam_access/pam_access.c
Even though NUL bytes are not supposed to show up in a configuration file, treat them properly and avoid out of boundary accesses.
Proof of Concept (compile with -fsanitize=address):
1. Create access.conf file with NUL byte at start of line
```
dd if=/dev/zero of=/tmp/access.conf bs=1 count=1
```
2. Use pam_access.so in e.g. /etc/pam.d/passwd
```
password  required    pam_access.so     accessfile=/tmp/access.conf
```
3. Run passwd
```
$ passwd
SUMMARY: AddressSanitizer: stack-buffer-overflow (/usr/lib/security/pam_access.so+0xf1ed) in login_access
```
=> pam_access: fix nul byte handling in config

configure.ac, modules/pam_timestamp/hmac_openssl_wrapper.c
This is a follow-up to my notes on #644.
The changes are mainly:
1. Ensure memory buffers with key material should always be wiped. This limits exposure of those buffers. This is mostly defense-in-depth, as those buffers are never exposed to the caller (error paths).
2. Prefer proper APIs for retrieving CSRNG data like OpenSSL's `RAND_priv_bytes` and `getrandom(5)`. As this is a wrapper for OpenSSL the call to `RAND_priv_bytes` is tried first, with `getrandom(5)` tried second. Only if both fail, a fallback to reading `/dev/urandom` is tried (which based on the implementation of `RAND_priv_bytes` is likely to fail too at this point).
I also added some checks for `PAM_NONNULL` to some of the functions to have the compiler check their inputs for valid pointers (as those checks were not …
=> pam_timestamp: OpenSSL wrapper updates

conf/pam_conv1/pam_conv_y.y, libpam/pam_misc.c, libpamc/pamc_load.c, modules/pam_access/pam_access.c, modules/pam_faillock/faillock.c, modules/pam_filter/pam_filter.c, modules/pam_issue/pam_issue.c, modules/pam_listfile/pam_listfile.c, modules/pam_mkhomedir/mkhomedir_helper.c, modules/pam_namespace/pam_namespace.c, modules/pam_unix/md5_crypt.c, modules/pam_unix/support.c, modules/pam_xauth/pam_xauth.c
These functions are easier to review than a combination of malloc, strcpy, and strcat.
=> treewide: use asprintf/strdup for string creations

modules/pam_motd/pam_motd.c
Prevent signed integer overflow if too many motd files are encountered. Use the easiest approach for such an unlikely scenario.
=> pam_motd: fail if too many motd files encountered

modules/pam_timestamp/pam_timestamp.c
If the pointer variable pwd is null, then a null pointer dereference problem occurs when fetching the contents of pw_uid and pw_name from the pwd variable.
To avoid this problem, I think we should return the value of the variable retval directly after determining that pwd is null.
https://github.com/linux-pam/linux-pam/issues/677
=> pam_timestamp_check: fix potential null pointer dereference on error path

modules/pam_unix/passverify.c
`setup_signals()` and thus its signal handler patched in this PR are used by the `unix_chkpwd` and `unix_update` helper programs. These programs communicate their completion status to the calling process by exit code, using one of the `PAM_*` error codes - or normally `PAM_SUCCESS`. Unfortunately, before the change proposed here, the signal handler would use the signal number as the exit code. The intercepted signals are generally low-numbered and are likely to clash with `PAM_*` error codes, confusing the caller.
Luckily, they would not normally clash with `PAM_SUCCESS`, which is 0, and the code has an explicit check for `sig > 0`. While on some obscure systems (e.g., with "sub-signals" on SPARC) the signal handler may be called with more than just the signal number encoded in its …
=> unix_chkpwd, unix_update: Use exit codes 128+ on signals

libpam/pam_handlers.c, libpam/pam_misc.c, libpam/pam_private.h, modules/pam_exec/pam_exec.c, modules/pam_filter/pam_filter.c, modules/pam_listfile/tst-pam_listfile-retval.c, modules/pam_motd/pam_motd.c, modules/pam_permit/tst-pam_permit-retval.c
This PR introduces a wrapper around getline, called pam_getline, and uses it within libpam to get rid of fgets calls.
Since this is mostly used when parsing configuration files, it fixes some issues with current code.
See this weird configuration file for example:
```
and this is another line
\
\
\
word
line1 \
line2
password  required    pam_unix.so       yescrypt shadow try_first_pass \
minlen=0
```
- The current code considers "and this is another line" as a new line which is parsed, even though the escaped newline in the comment should indicate otherwise.
- The "word" line has preceding whitespaces because the current code does not handle them well with escaped newlines.
- "line1" and "line2" should be separate lines, yet the current code merges them into "line1 line2"
Having NUL …
=> libpam: support arbitrarily long configuration file lines

modules/pam_env/pam_env.c, modules/pam_env/tst-pam_env-retval.c
A memory leak can occur if DEFAULT or OVERRIDE are supplied multiple times in a line.
While at it, prepare a change for later pam_assemble_line port from libpam to pam_env by removing the usage of a fixed sized stack variable. It doesn't take copying actually.
Also improve debug and error messages and reduce variable visibility so it is easier to trace where variables are actually used (which makes the debug and error message adjustment also easier to verify).
=> pam_env: various cleanups

modules/pam_faillock/pam_faillock.c, modules/pam_listfile/pam_listfile.c, modules/pam_wheel/pam_wheel.c
The modules pam_faillock, pam_listfile and pam_wheel could silently truncate very long arguments coming from pam configuration files.
This was true for pam_listfile even before the arbitrary line length adjustment.
=> modules: prevent config truncations

modules/pam_exec/pam_exec.8.xml, modules/pam_exec/pam_exec.c
I'm developing an integration between linux PAM and OpenZFS native encryption for datasets to automatically encrypt users' home directories. 
The pam_exec module fitted almost 100% to unlock the user's home directory dataset provided the password is used also as the key source for the dataset.
Apparently, when the password changes, the key must also be updated to keep them in sync.
However pam_exec exposes the password thru expose_authtok for auth PAM_TYPE only. This trivial patch allows pam_exec to expose the new password when the user or admin changes the password. 
please consider accepting this patch into the master branch.
Best regards
Anton Gubarkov.
=> pam_exec: allow also expose_authtok for password PAM_TYPE

modules/pam_namespace/pam_namespace.c
If more than INT_MAX uids are found in a configuration line, the variable `count` would trigger a signed integer overflow.
If more than UINT_MAX uids are found in a configuration line, then the `num_uids` counter is invalid, which could eventually lead to out of boundary accesses.
Also make sure that size multiplication for malloc does not overflow.
=> pam_namespace: validate amount of uids in config

configure.ac
Even if these checks reveal that a function does not exist there is no corresponding HAVE_* check in source files.
Noticed while adding `strndup` to https://github.com/linux-pam/linux-pam/pull/684.
=> configure.ac: remove unneeded function checks

modules/pam_unix/support.c
The `_unix_getpwnam` function takes a bit of refactoring to be getline-compatible.
I have performed every step in a single commit to allow easier review.
Feel free to squash or ask me to squash them if review is complete.
Since I have no NIS environment, the NIS code path is not tested (compiles on my system though).
=> pam_unix: use getline in _unix_getpwnam

modules/pam_access/pam_access.c, modules/pam_exec/pam_exec.c, modules/pam_faillock/faillock_config.c, modules/pam_limits/pam_limits.c, modules/pam_listfile/pam_listfile.c, modules/pam_securetty/pam_securetty.c, modules/pam_sepermit/pam_sepermit.c, modules/pam_unix/pam_unix_passwd.c, modules/pam_unix/passverify.c, modules/pam_xauth/pam_xauth.c
This PR changes most `fgets` calls to `getline`. Commits in this PR are quite simple, because we were able to prepare the affected code paths in previous commits.
The `pam_env` module is too complex to be added into this PR because it involves porting `_pam_assemble_line` and will be done in a separate PR.
The `pam_unix` module has one separate PR because of the involved complexity: https://github.com/linux-pam/linux-pam/pull/694
=> modules: use getline instead of fgets

modules/pam_unix/passverify.c
Initially, when pam_unix.so verified the password, it used to try to obtain the shadow password file entry for the given user by invoking getspnam(3), and only when that didn't work and the effective uid was nonzero, pam_unix.so used to invoke the helper as a fallback.
When SELinux support was introduced by commit
67aab1ff5515054341a438cf9804e9c9b3a88033, the fallback was extended also for the case when SELinux was enabled.
Later, commit f220cace205332a3dc34e7b37a85e7627e097e7d extended the fallback conditions for the case when pam_modutil_getspnam() failed with EACCES.
Since commit 470823c4aacef5cb3b1180be6ed70846b61a3752, the helper is invoked as a fallback when pam_modutil_getspnam() fails for any reason.
The ultimate solution for the case when pam_unix.so does not have permissions to …
=> pam_unix/passverify: always run the helper to obtain shadow password file entries

libpam/pam_handlers.c
The declaration uses static keyword, the definition does not. Fix the definition, because the function is only used in this file.
=> libpam: use correct function definition

doc/adg/Linux-PAM_ADG.xml, libpam/include/security/_pam_macros.h, libpam/pam_audit.c, libpam/pam_dispatch.c, libpam/pam_end.c, libpam/pam_misc.c, modules/pam_env/pam_env.c, modules/pam_filter/pam_filter.c, modules/pam_namespace/namespace.conf.5.xml, modules/pam_namespace/pam_namespace.c, modules/pam_namespace/pam_namespace.h, modules/pam_unix/pam_unix.8.xml
Typos in comments and in documentation fixed.
=> treewide: fix typos

modules/pam_env/pam_env.c, modules/pam_env/tst-pam_env-retval.c
The arguments in a `pam_env` configuration file can be substituted with environment variables or PAM items. This expansion can become larger than the original input line.
Allow them to grow arbitrarily since PAM environment variables can handle such situations already. Also, this is a preparation to use getline for configuration file parsing.
This PR includes a test case for variable substitution and how `pam_env` handles escaped newlines. There is a subtle difference between libpam and pam_env: The backslash character is not replaced by a blank but removed as well. The added test covers this.
=> pam_env: allow long argument expansions

configure.ac, libpam/pam_delay.c
Use getrandom to retrieve random numbers for delay calculation.
If it fails or is not available, keep using current algorithm.
The getrandom call has been introduced in 4936f7dc386e0f0e16d4835954ab061e87399912.
=> libpam: use getrandom if possible

modules/pam_access/pam_access.c
If a very long group name is supplied, do not truncate it. It is safe to work directly on the supplied token, which is also already done in user_match, from where group_match is also called.
Fixes issue introduced with 3a9cd90a97c64a66d2912df5109793ee9158858c.
No release affected.
=> pam_access: avoid group name truncation

modules/pam_unix/passverify.c, modules/pam_unix/unix_chkpwd.c
This could allow users with very long names to impersonate a user with a 255 characters long name.
The check if the argument argv[1] actually matches the user name implies that "user" can unconditionally be set to argv[1]: If they are equal, the strings are obviously equal. If they are not or if null is returned by getuidname, "user" is set to argv[1] anyway.
This way, the static buffer can be safely removed because the result of getpwuid() is not stored, which means that subsequent calls to such functions can safely overwrite their internal buffers.
It would be difficult to justify this as a proper security issue, therefor a public PR. It takes a user name with 256+ characters which starts with the same 255 characters of another user who must have exactly 255 characters.
Also, having …
=> pam_unix: do not truncate user names

modules/pam_env/pam_env.c, modules/pam_env/tst-pam_env-retval.c
Otherwise it is not possible to add \ into an environment variable.
=> pam_env: allow escaping of escape character

modules/pam_listfile/pam_listfile.c
The characters \r and \n are replaced by NUL byte. Treat a line which is empty after removal of \r just like lines which are empty after the removal of \n.
=> pam_listfile: treat \r like \n

modules/pam_access/pam_access.8.xml, modules/pam_access/pam_access.c
This pull request adds a quiet_log option to pam_access. If quiet_log is set, no "access denied" message is written to the syslog. Closes #706.
=> pam_access: add quiet_log option

modules/pam_access/pam_access.c, modules/pam_lastlog/pam_lastlog.c, modules/pam_listfile/pam_listfile.c, modules/pam_localuser/pam_localuser.c, modules/pam_sepermit/pam_sepermit.c, modules/pam_succeed_if/pam_succeed_if.c, modules/pam_usertype/pam_usertype.c
Calling an exported function from the module is unsafe as there is no guarantee that the function that will be actually called is the one that is provided by the module.
=> modules: do not call pam_sm_authenticate

libpam/pam_modutil_searchkey.c, modules/pam_env/pam_env.c, modules/pam_faillock/faillock_config.h, modules/pam_pwhistory/opasswd.c
These are leftovers from fgets usages.
=> treewide: remove unused defines

modules/pam_succeed_if/Makefile.am, modules/pam_succeed_if/pam_succeed_if.c, modules/pam_succeed_if/tst-pam_succeed_if-retval.c
This PR prevents truncation of very long fields like user, rhost etc. These items can be set by pam_set_item and are therefor not purely related to the feature of arbitrarily long configuration lines.
Also empty strings should not be treated as the numerical value 0.
For easier testing and verification, I have added a new unit test file.
=> pam_succeed_if: handle long and illegal values

modules/pam_pwhistory/opasswd.c, modules/pam_pwhistory/opasswd.h, modules/pam_unix/passverify.c, modules/pam_unix/passverify.h
Instead of annotating the function definition with the format attribute
annotate the declaration, so the annotation is visible at call sites.
=> Annotate declaration with format attribute

modules/pam_pwhistory/Makefile.am, modules/pam_pwhistory/pam_pwhistory.c
Apply the same logic of pam_unix Makefile adjustment for pw_history as well. Reference commit is
cb9f88ba944d56c0b6c65be18500f7d56c9f514c.
The helper pwhistory_helper(8) is only called from code enabled when SELinux support is enabled.
CC @cgzones: It would be nice if you could review this PR.
=> pam_pwhistory: build pwhistory_helper only with SELinux enabled

modules/pam_unix/pam_unix_passwd.c, modules/pam_unix/passverify.c
The returned value stored in pwd from _unix_getpwnam is inserted into
pam handler through pam_set_data. Do not manually free the value.
Also check getline return value for != -1 instead of == -1.
Fixes 8f2ca5919b26843ef774ef0aeb9bf261dec943a0 and
73d009e9ea8edafc18c7fe3650b25dd6bdce88c1. No release affected.
Signed-off-by: Tobias Stoeckmann <tobias@stoeckmann.org>
=> pam_unix: fix regressions

modules/pam_unix/pam_unix_passwd.c, modules/pam_unix/passverify.c
The opasswd file shall not use comma as a separator. Enforce colon just like pam_pwhistory does as well.
A comma can be part of a user name, although its usage is discouraged. If such a user exists, it could happen that stored passwords of another user are checked.
Potentially dangerous use of `,` separator spotted with @BenBE.
1. Use `remember` option in /etc/pam.d/passwd:
```
password  required    pam_unix.so       shadow try_first_pass remember=10
```
2. Create `/etc/security/opasswd` file
```
install /dev/null -m 600 /etc/security/opasswd
```
3. Create user `a,b` and set its password three times (first two will be added to /etc/security/opasswd eventually)
```
useradd --badname a,b
passwd a,b           # e.g. "abc"
sudo -u a,b passwd   # e.g. "def"
sudo -u a,b passwd …
```
=> pam_unix: do not allow comma as field separator

modules/pam_pwhistory/opasswd.c
Users may have a hash character in their name, which would be removed. This in turn effectively defeats the purpose of pam_pwhistory for the user.
1. Use pam_pwhistory as suggested in its manual page in /etc/pam.d/passwd:
```
password     required       pam_pwhistory.so
password     required       pam_unix.so        use_authtok shadow
```
2. Create user `a#b` and set its password twice
```
useradd --badname a#b
passwd a#b             # e.g. "abc"
passwd a#b             # e.g. "def"
```
3. Try to use the first password again
```
passwd a#b             # first password (in this example "abc")
```
The password should not be accepted. Yet, every call adds a new line to /etc/security/opasswd instead, because the removal of comments makes the lines unparseable for …
=> pam_pwhistory: parse opasswd lines verbatim

configure.ac, doc/Makefile.am
* configure: require libsystemd on --enable-logind
Fail if `--enable-logind` is specified while libsystemd cannot be found, so the feature is reliably enabled on success.
* doc: do not clean bootstrapped files
The two files custom-html.xsl and custom-man.xsl are created at configure time.  Only delete them on `make distclean` instead of `make clean` to be able to re-generate manual pages afterwards.
=> Two build system tweaks

NEWS, configure.ac, modules/pam_namespace/pam_namespace.c, po/Linux-PAM.pot
* configure.ac (AC_INIT): Raise version to 1.6.0.
* po/Linux-PAM.pot (Project-Id-Version): Likewise.
* NEWS: Update.
Resolves: https://github.com/linux-pam/linux-pam/issues/690
=> Prepare for 1.6.0 release

modules/pam_namespace/pam_namespace.c
missing include causes compilation errors.
closes #733
=> include stdint.h in pam_namespace.c

libpam/pam_handlers.c
If configure option --enable-read-both-confs is used, the build fails with 1.6.0 due to missing stack level depth argument passed to _pam_parse_conf_file.
Solves https://github.com/linux-pam/linux-pam/issues/736.
=> libpam: fix build with --enable-read-both-confs

modules/pam_env/pam_env.c
The VENDORDIR define has to be checked after config.h inclusion, otherwise the ifdef test always yields false.
Fixes: 6135c45347b6 ("pam_env: Use vendor specific pam_env.conf and environment as fallback")
Spotted while analysing https://github.com/linux-pam/linux-pam/issues/738.
=> pam_env: check VENDORDIR after config.h inclusion

modules/pam_env/pam_env.c
* modules/pam_env/pam_env.c (_parse_config_file) [!USE_ECONF && VENDOR_DEFAULT_CONF_FILE]: Do not fallback to vendor pam_env.conf file if the config file is specified via module arguments.
Link: https://github.com/linux-pam/linux-pam/issues/738
Fixes: v1.5.3~69 ("pam_env: Use vendor specific pam_env.conf and environment as fallback")
=> pam_env: fix --enable-vendordir fallback logic

modules/pam_env/pam_env.c
The libeconf routines do not remove escaped newlines the way we want to process them later on. Manually remove them from values.
=> pam_env: remove escaped newlines from econf lines

libpam_misc/help_env.c
Theoretically the int might overflow. Use a size_t to protect this function which might be called from an application, because it is exposed through pam_misc.h header.
=> libpam_misc: use size_t for sizes

modules/pam_unix/passverify.c
Later checks will print a warning if daysleft is 0. If password aging is disabled, leave daysleft at -1.
Fixes 9ebc14085a3ba253598cfaa0d3f0d76ea5ee8ccb.
Resolves https://github.com/linux-pam/linux-pam/issues/743
=> pam_unix: do not warn if password aging disabled

configure.ac
React on actual test if SELinux is available, not just if SELinux should be tested for.
Currently the supposedly disabled binaries are still installed even if SELinux is not available.
Fixes: cb9f88ba944d ("pam_unix: build unix_update only with SELinux enabled")
Reported here: https://wiki.linuxfromscratch.org/blfs/ticket/19142
=> build: correctly set WITH_SELINUX conditional

modules/pam_namespace/namespace.init
Given that sed is considered a more lightweight dependency than awk, and since sed is used by pam_namespace_helper anyway, use sed instead of awk in namespace.init as well.
* modules/pam_namespace/namespace.init: Use sed instead of awk to obtain the UMASK value from /etc/login.defs.
=> pam_namespace: use sed instead of awk in namespace.init

modules/pam_faildelay/pam_faildelay.c
Fix the following warning reported by gcc on 32bit platforms:
```
pam_faildelay.c: In function 'pam_sm_authenticate':
pam_faildelay.c:104:34: error: comparison of integer expressions of different signedness: 'long int' and 'unsigned int' [-Werror=sign-compare]
104 |           if (delay < 0 || delay > UINT_MAX)
|                                  ^
pam_faildelay.c:123:32: error: comparison of integer expressions of different signedness: 'long int' and 'unsigned int' [-Werror=sign-compare]
123 |         if (delay < 0 || delay > UINT_MAX / S_TO_MICROS)
|                                ^
```
* modules/pam_faildelay/pam_faildelay.c (pam_sm_authenticate): Cast "delay" to "unsigned long" in comparisons with unsigned int.
Fixes: dd87776d3683 ("pam_faildelay: validate parameter ranges")
=> pam_faildelay: fix compilation warnings on 32bit platforms

modules/pam_pwhistory/opasswd.c, modules/pam_unix/bigcrypt.c, modules/pam_unix/passverify.c, modules/pam_userdb/pam_userdb.c
The manual page of crypt_r(3) recommends to zero the entire data object.
=> modules: zero out crypt_r(3) data before usage

modules/pam_faildelay/pam_faildelay.c
Use `long long` on 32 bit systems to also support `UINT_MAX` without falling back to strtoul, which automatically converts a negative number to a positive value.
While at it, prevent more invalid numbers.
This line triggers a syslog warning:
```auth            optional        pam_faildelay.so delay=abc```
This one does not:
```auth            optional        pam_faildelay.so delay=1abc```
=> pam_faildelay: improve delay parsing

Makefile.am, configure.ac, libpam/Makefile.am, libpam/include/security/_pam_macros.h, libpam_internal/Makefile.am, libpam_internal/pam_debug.c, libpam_misc/Makefile.am, libpamc/Makefile.am, modules/pam_access/Makefile.am, modules/pam_debug/Makefile.am, modules/pam_env/Makefile.am, modules/pam_group/Makefile.am, modules/pam_issue/Makefile.am, modules/pam_lastlog/Makefile.am, modules/pam_limits/Makefile.am, modules/pam_mail/Makefile.am, modules/pam_mkhomedir/Makefile.am, modules/pam_motd/Makefile.am, modules/pam_permit/Makefile.am, modules/pam_stress/Makefile.am, modules/pam_time/Makefile.am, modules/pam_unix/Makefile.am, tests/Makefile.am
Move function bodies from headers into dedicated object files stored in libpam_internal. This library won't be installed.
Keep the debug function body in header, even though disabled when building Linux-PAM, to stay API compatible with previous versions.
=> libpam_internal: supply debug functionality

modules/pam_unix/pam_unix_acct.c, modules/pam_unix/support.c
The geteuid check does not cover all cases. If a program runs with elevated capabilities like CAP_SETUID then we can still check credentials of other users.
Keep logging for future analysis though.
Resolves: https://github.com/linux-pam/linux-pam/issues/747
Fixes: b3020da7da38 ("pam_unix/passverify: always run the helper to obtain shadow password file entries")
=> pam_unix: try to set uid to 0 for unix_chkpwd

libpam/Makefile.am, libpam/pam_handlers.c, libpam_internal/Makefile.am, libpam_internal/include/pam_line.h, libpam_internal/pam_line.c, modules/pam_env/Makefile.am, modules/pam_env/pam_env.c
The pam_assemble_line function is renamed to pam_line_assemble and moved into libpam_internal so it can be shared across libpam and the pam_env module.
Applied renaming to all other relevant functions and data structures so it is easier to locate them in files.
=> libpam_internal: introduce pam_line

modules/pam_limits/pam_limits.c
- Remove whitespaces around value in limits.conf
- Keep copy of input line for error messages
Fixes https://github.com/linux-pam/linux-pam/issues/761.
=> pam_limits: fix sscanf removal regression

configure.ac, modules/pam_unix/support.c
If NIS/YP headers are missing, do not enable NIS support.
One such scenario could be that libnsl library is installed without its development package. One distribution which separate between binaries and header files is Debian.
Should fix https://github.com/linux-pam/linux-pam/issues/772
=> Improve NIS/YP build checks

modules/pam_unix/passverify.c
Before the change pam_unix has different behaviours for a user with empty password for these two `/etc/shadow` entries:
nulloktest:$6$Yy4ty2jJ$bsVQWo8qlXC6UHq1/qTC3UR60ZJKmKApJ3Wj7DreAy8FxlVKtlDnplFQ7jMLVlDqordE7e4t49GvTb.aI59TP0:1::::::
nulloktest::1::::::
The entry with a hash was rejected and the entry without was accepted.
The rejection happened because 9e74e90147c "pam_unix: avoid determining if user exists" introduced the following rejection check (slightly simplified):
...
} else if (p[0] == '\0' && nullok) {
if (hash[0] != '\0') {
retval = PAM_AUTH_ERR;
}
We should not reject the user with a hash assuming it's non-empty. The change does that by pushing empty password check into `verify_pwd_hash()`.
`NixOS` generates such hashed entries for empty passwords as if they were non-empty …
=> pam_unix: allow empty passwords with non-empty hashes

modules/pam_env/pam_env.8.xml
Document that pam_env.so is only called by pam_setcred() and not by pam_authenticate() when added to the auth stack (#680)
=> pam_env: document when the module is executed

libpam/pam_start.c
Call bindtextdomain() only when both the function is available and the build is configured with --enable-nls.
* libpam/pam_start.c (_pam_start_internal): Guard bindtextdomain() invocation with ENABLE_NLS.
Complements: v1.6.0~244 ("pam_start.c: call bindtextdomain() to expose Linux-PAM locales")
Resolves: https://github.com/linux-pam/linux-pam/pull/773
=> pam_start.c: do not call bindtextdomain() unless nls is enabled

doc/man/pam_get_data.3.xml, tests/Makefile.am, tests/tst-pam_get_data.c
The manual for pam_get_data(3) states:
Module data not found or there is an entry, but it has the value `NULL`.
However, if the data is set and then unset, no error is returned.
So when checking for the value, actually ensure that it's not `NULL`.
---
The root issue for this is that `pam_set_data` does not really ever unsets the data, so ~~I'll suggest another alternative in a new PR~~ (done in #781), but this is the quicker implementation.
As per this, add tests since we had no get tests.
Also fix null pointer access when getting the data without a pointer receiver, I think it can be useful in some cases and I don't think we should error in such case, but if that's not wanted, we could just return `PAM_SYSTEM_ERROR`
=> pam_get_data: manual page claims that PAM_NO_MODULE_DATA is returned in case of NULL data value

CHANGELOG
Dag-Erling Smørgrav's name was encoded using some encoding other than UTF-8 (that line predates the UTF-8 consensus). This changes it to use UTF-8, so that it renders properly and so that editors that guess the file is UTF-8 do not get confused about it.
=> Fix CHANGELOG encoding

modules/pam_faillock/pam_faillock.c, modules/pam_namespace/pam_namespace.c, modules/pam_rootok/pam_rootok.c, modules/pam_timestamp/pam_timestamp.c
* modules/pam_faillock/pam_faillock.c: close file when it will not be
used anymore.
* modules/pam_faillock/pam_faillock.c: close file when it will not be
used anymore.
* modules/pam_timestamp/pam_timestamp.c: close file when an error is
detected.
* modules/pam_namespace/pam_namespace.c: free SELinux context before
returning.
* modules/pam_namespace/pam_namespace.c: free SELinux context when an
error is detected.
```
Error: RESOURCE_LEAK (CWE-772):
Linux-PAM-1.6.0/modules/pam_faillock/pam_faillock.c:247: open_fn: Returning handle opened by "audit_open".
Linux-PAM-1.6.0/modules/pam_faillock/pam_faillock.c:247: var_assign: Assigning: "audit_fd" = handle returned from "audit_open()".
Linux-PAM-1.6.0/modules/pam_faillock/pam_faillock.c:256: noescape: Resource "audit_fd" is not freed or …
```
=> Assorted static analyzer fixes

libpam/pam_item.c, tests/tst-pam_set_item.c
This also prevents a possible segfault when pam_set_item tries to convert an empty service_name to lower case.
=> pam_set_item: disallow setting service to NULL

configure.ac, libpam/pam_modutil_searchkey.c, libpam_internal/Makefile.am, libpam_internal/include/pam_econf.h, libpam_internal/pam_econf.c, modules/pam_env/Makefile.am, modules/pam_env/pam_env.c, modules/pam_shells/Makefile.am, modules/pam_shells/pam_shells.c
econf_readConfig* calls are supporting the Linux Userspace API (UAPI) Group  chapter "Configuration Files Specification".
See: https://uapi-group.org/specifications/specs/configuration_files_specification/
=> Replacing old econf_readDirs by econf_readConfig if available.

modules/pam_faillock/main.c
Since audit_log_acct_message() was decorated with warn_unused_result attribute, compilation of faillock helper produces the following diagnostics:
main.c: In function 'do_user':
main.c:250:25: warning: ignoring return value of 'audit_log_acct_message' declared with attribute 'warn_unused_result' [-Wunused-result]
Given that this helper has never been picky about audit, e.g. audit_open() errors do not affect its exit status, just silence this new warning.
* modules/pam_faillock/main.c [HAVE_LIBAUDIT] (do_user): Silence compilation warning.
=> pam_faillock: silence compilation warning

configure.ac
=> configure.ac: fix typo in the help message for --enable-lastlog

libpam_misc/misc_conv.c
Use the canonical terminal mode (line mode) and set ECHOCTL to prevent cursor escape from the login prompt using arrows or escape sequences.
ICANON is the default in most cases anyway. ECHOCTL is default on tty, but for example not on pty, allowing cursor to escape.
Stanislav Brabec <sbrabec@suse.com>
=> libpam_misc: Use ECHOCTL in the terminal input

libpam/include/pam_inline.h, modules/pam_access/access.conf.5.xml, modules/pam_access/pam_access.c
Following up on #114 and #186.  It appears that the original author, @blueskycs2c, has been inactive for several years.  The change has been [rebased as requested](https://github.com/linux-pam/linux-pam/pull/186#issuecomment-1650565201) by @t8m.
=> pam_access: Support UID and GID in access.conf

modules/pam_limits/Makefile.am, modules/pam_limits/pam_limits.c
The utmp database is unreliable for counting logged in users, since there is no standard which defines who should create an entry at which time for which reason. And it has a Y2038 problem with glibc/x86-64. Query systemd-logind for the number of user sessions instead.
Using systemd-logind requires that "maxlogins" is at minimum "2", since pam_systemd for the first login calls "systemd --user", which calls again the PAM stack. But this time there is already an user session, so with maxlogins=1 systemd would get a denied by PAM and the session management is in an undefined state.
=> pam_limits: use systemd-logind instead of utmp (#822)

modules/pam_userdb/pam_userdb.c
crypt_r can return a pointer into a provided crypt_data struct.  Callers should not modify the string returned by crypt_r after freeing the corresponding crypt_data struct.
=> pam_userdb: don't overwrite free'd memory

meson.build, modules/module-meson.build
If vendordir is enabled, the distribution provided configuration files should be in below this directory and not in /etc.
This was already wrong in Makefile.am before, was forgotten when adding vendordir support for pam_env.
=> pam_env: install environment file in vendordir

examples/tty_conv.c
Found by Linux Verification Center (linuxtesting.org) with SVACE.
Reporter: Pavel Nekrasov ([p.nekrasov@fobos-nt.ru](mailto:p.nekrasov@fobos-nt.ru)).
Organization: Fobos-NT ([info@fobos-nt.ru](mailto:info@fobos-nt.ru)).
=> examples/tty_conv: fix potential out of bound write in readline()

meson.build, modules/pam_userdb/pam_userdb.c
gdbm_close() returns void, so we cannot use that as return argument, if the calling function returns int.
=> pam_userdb: don't return void result as int

modules/pam_access/access.conf.5.xml, modules/pam_access/pam_access.c
* modules/pam_access/pam_access.c: match the local address regardless of
the IP version in use.
* modules/pam_access/access.conf.5.xml: `LOCAL` keyword behaviour
explanation was focused on the development internals. Let's clarify it
by rephrasing it to something a sysadmin can understand.
In some circumstances the `localhost` may be translated to IPv4 or IPv6,
but the configuration file only indicated the address for one of the two
versions. Since the originating value is set in `PAM_RHOST` and PAM has
no control over it, let's match the local addresses regardless of the IP
version in use.
Resolves: https://issues.redhat.com/browse/RHEL-23018
Resolves: https://issues.redhat.com/browse/RHEL-39943
=> pam_access_fixes

NEWS, libpam/include/security/_pam_types.h, meson.build, po/Linux-PAM.pot, po/meson.build
* meson.build: Raise project version to 1.7.0.
* po/meson.build: Likewise.
* po/Linux-PAM.pot (Project-Id-Version): Likewise.
* libpam/include/security/_pam_types.h (__LINUX_PAM_MINOR__): Update.
* NEWS: Update.
Resolves: https://github.com/linux-pam/linux-pam/issues/844
=> Prepare for 1.7.0 release

doc/specs/meson.build
Fixes: https://github.com/linux-pam/linux-pam/issues/850
Add 'native : true' to build config of padout.
Changes to be committed:
modified:   doc/specs/meson.build
=> Build padout as native binary

doc/guide-meson.build, meson.build
While building any documentation requires xsltproc, only the PDF documentation requires fop, which is dependency-heavy, and not always available (e.g. it is not included in RHEL).  This allows the HTML documentation to be built while skipping the PDFs.
/cc @ikerexxe
=> doc: make PDF documentation optional

modules/pam_access/access.conf.5.xml, modules/pam_access/pam_access.8.xml, modules/pam_access/pam_access.c
* modules/pam_access/pam_access.c: separate resolving if IP addesses from hostnames. Don't resolve TTYs or display variables as hostname (#834). Add "nodns" option to disallow resolving of tokens as hostname.
* modules/pam_access/pam_access.8.xml: document nodns option
* modules/pam_access/access.conf.5.xml: document that hostnames should be written as FQHN.
=> pam_access: rework resolving of tokens as hostname

meson.build, meson_options.txt, modules/module-meson.build, modules/pam_issue/pam_issue.c, modules/pam_limits/pam_limits.c, modules/pam_timestamp/pam_timestamp.c
The systemd functionality used here is also supported by elogind. Search for libelogind as well and use the appropriate headers.
Not sure what approach is wanted here. I opted to not change the semantics of the `logind` option and just search for both libraries.
=> meson: support elogind as a logind provider

meson.build
sizeof is meant for *types*, and the test program produced by it has incorrect syntax
__NR_keyctl something;
and will always fail to compile.
=> meson.build: correct check for existence of two preprocessor defines

modules/pam_unix/pam_unix_passwd.c
When configured using -Dpam-debug=true, _pam_unix_approve_pass prints
a diagnostic message with addresses of password strings.  Apparently,
since the times predating the git history of the project in this
diagnostic message the addresses of the old and new passwords were
mixed up.
=> pam_unix: fix diagnostic message in debug mode

meson.build
When build is configured with a custom prefix, ignore the value of systemdsystemunitdir pkgconfig variable if it doesn't start with that custom prefix.
Resolves: https://github.com/linux-pam/linux-pam/issues/863
=> meson.build: fix pam_namespace.service installation with custom prefix

modules/pam_unix/bigcrypt.c, modules/pam_unix/passverify.c
Given that the crypt_data storage passed to crypt_r is cleared afterwards, there is no point to clear the string returned by crypt_r. This also fixes the issue with those crypt_r implementations that can return a pointer to read-only memory.
Resolves: https://github.com/linux-pam/linux-pam/issues/866
=> pam_unix: do not overwrite the string returned by crypt_r

meson.build, po/meson.build
These should all be native programs found on the build machine. We should not try to execute them via QEMU. Users would therefore expect to configure them using the native file, not the cross file.
See https://mesonbuild.com/Reference-manual_functions.html#find_program.
=> meson: Find programs using the native file only, not the cross file

modules/pam_namespace/pam_namespace.c
The case in which protect_dir() returns an error and the flag POLYDIR_CREATE (flag "create" in namespace.conf) is not set was not handled. Therefore, the program continued without a polydir and returned later on failed mount(2) or stat(2) calls.
=> pam_namespace: fix logic in return value handling

modules/pam_issue/pam_issue.c
* modules/pam_issue/pam_issue.c (pam_sm_authenticate): Free issue_prompt before assigning a new string.
=> pam_issue: fix potential memory leak when PAM_USER_PROMPT is set

meson.build, modules/pam_access/pam_access.c, modules/pam_canonicalize_user/pam_canonicalize_user.c, modules/pam_env/pam_env.c, modules/pam_mail/pam_mail.c
Enable the compiler warning -Wzero-as-null-pointer-constant introduced in GCC 15 and also available on Clang and replace all found occurrences.
=> treewide: replace 0 with NULL for pointers

modules/pam_limits/limits.conf, modules/pam_limits/limits.conf.5.xml, modules/pam_limits/pam_limits.c
This adds support for the rttime (RLIMIT_RTTIME) limit in pam_limits. Updated documentation, man page, and pam_limits.conf comments accordingly.
=> pam_limits: Add support for rttime (RLIMIT_RTTIME)

examples/tty_conv.c
TCGETA/TCSETA/TCSETAW are not in posix and not in some OSes, better use the posix-defined tcgetattr/tcsetattr.
=> tty_conv: Replace TCGETA/SETAF/SETAW with posix tcgetattr/tcsetattr

modules/pam_faillock/pam_faillock.8.xml, modules/pam_faillock/pam_faillock.c
* modules/pam_faillock/pam_faillock.c: when `auth` stack isn't run skip
clearing the user's failed attempt record during `account` stack.
Automate services, like `crond` or `systemd-user`, skip the `auth` stack and directly invoke the `account` stack. Thus, they can clear the user's failed attempt records. When `ignore_services` option is used, if the calling service matches one of the specified names, `pam_faillock` simply skips the logic for resetting the failed login counter.
Resolves: https://issues.redhat.com/browse/RHEL-32294
=> pam_faillock: skip clearing user's failed attempt

libpam/pam_modutil_cleanup.c, libpam/pam_modutil_getgrgid.c, libpam/pam_modutil_getgrnam.c, libpam/pam_modutil_getpwnam.c, libpam/pam_modutil_getpwuid.c, libpam/pam_modutil_getspnam.c, libpam/pam_modutil_private.h
Make sure that the buffer containing encrypted passwords (struct group, passwd and shadow) get's erased before free, so that they are not available anymore if the memory get allocated again.
=> pam_modutil_get*: overwrite password at free (#846)

doc/specs/draft-morgan-pam.raw
fixed typo error "libraray" to "library"
=> doc: fix typo in draft-morgan-pam.raw

meson.build, meson_options.txt, modules/module-meson.build, modules/pam_unix/passverify.c
[pwaccess](https://github.com/thkukuk/pwaccess) is a systemd socket activated service which provides passwd and shadow entries to root or the user of that entry to avoid having binaries owned by group shadow and/or setuid/setgid to do the authentication.
Reasons:
- avoid UID/GID shift with image based updates, so everything in /usr should be owned by root:root
- security, don't allow setuid/setgid binaries. Requested by:
- systemd developers (https://github.com/linux-pam/linux-pam/issues/902)
- our security team
Since with #912 pam_unix could behave different than today, I decided to only replace the `getspnam()` call in unix_chkpwd, so that unix_chkpwd does not need the setuid bit if pwaccessd is running. If not, unix_chkpwd will fallback to `getspnam()`. 
`pwaccess` itself got reviewed …
=> pam_unix: add support for pwaccessd (#902)

meson_options.txt
If libeconf support is enabled and no vendordir is set, use /usr/share/pam as default.
The old behavior (disabled vendordir) can be archived with `meson setup build -Dvendordir=''`, but at runtime there should be no difference if people don't use `/usr/share/pam`.
=> meson_options: set default vendordir (#933)
